### ISSUE TITLE
Wrong font shapes after \setmainfont

### ISSUE THREAD

**Issue by pmav99** [wspr/fontspec#104]
I think this is a bug, but I don't know if it is fontspec related or something is wrong with the fonts. Consider the following code. It typesets without problems. Upright text is upright, italic text is italic etc.

```latex
\documentclass{article}

\usepackage{fontspec}

%\setmainfont{GFS Artemisia}
\setmainfont{GFS Didot}

\begin{document}
    Regular text\\
    \textit{Italic text}\\
    \textbf{Bold text}\\
    \textbf{\textit{Bold Italic text}}
\end{document}
```

Now uncomment `\setmainfont{GFS Artemisia}` and recompile. At least on my computer, everything is typeset in Bold Italic GFS Didot! If you change `GFS Artemisia` with another font then everything is ok again...

I am on TeXLive 32 bit and I am using the OpenType fonts from here http://www.greekfontsociety.gr/pages/en_typefaces20th.html
```
XeTeX 3.1415926-2.2-0.9997.4 (TeX Live 2010)
kpathsea version 6.0.0
Compiled with ICU version 4.4 [with modifications for XeTeX]
Compiled with zlib version 1.2.3; using 1.2.3
Compiled with FreeType2 version 2.3.11; using 2.3.11
Compiled with fontconfig version 2.3.1; using 2.8.0
Compiled with libpng version 1.2.40; using 1.2.40
Compiled with xpdf version 3.02pl4
```
If you need any more info, I am at your disposal.

with regards,
Panos

**Comment by wspr** [comment]
Whatever this was, it's fixed.
