### ISSUE TITLE
fontspec calls 'xunicode' unconditionally even when run by lualatex

### ISSUE THREAD

**Issue by vp1981** [wspr/fontspec#107]
Hi.

I'm not sure if 'xunicode' package should be called unconditionally or not but this example

``` latex
\documentclass{article}

\usepackage{fontspec}

\setmainfont{DejaVu Serif}

\begin{document}

Hello, World!

\end{document}
```

processed by lualatex calls 'xunicode' package (excerpt from log file)

```
(/usr/local/opt/texlive/2010/texmf-dist/tex/latex/euenc/eu2lmr.fd
File: eu2lmr.fd 2009/10/30 v1.6 Font defs for Latin Modern
)
luaotfload | load font: auto-selecting default features for script: dflt (was l
atn)(load: /home/lomov/.texlive2010/texmf-var/luatex-cache/generic/fonts/otf/te
mp-lmroman10-regular.lua))
(/usr/local/opt/texlive/2010/texmf-dist/tex/xelatex/xunicode/xunicode.sty
File: xunicode.sty 2010/11/06 v0.96 provides access to latin accents and many o
ther characters in Unicode lower plane
)
```

The same with TL11 (pretest).

**Comment by lpar** [comment]
I just hit this problem because I don't have XeTeX installed, only LuaTeX. Installing xunicode seems to fix it.

**Comment by wspr** [comment]
Loading xunicode is intentional -- it is necessary for setting up commands for accents and other characters. In the slightly longer term we are looking at folding what xunicode does back into fontspec and even LaTeX more generally but I can't promise anything soon.

**Comment by lpar** [comment]
Ah. In that case, the problem is presumably that xunicode isn't marked as a dependency for fontspec, so tlmgr didn't install it. (I was also confused by the fact that xunicode is described as a XeTeX utility, is under /macros/xetex on CTAN, and [has code in](http://tug.ctan.org/macros/xetex/latex/xunicode/xunicode.sty) stating that it only works with XeTeX.)
