### ISSUE TITLE
support new Indic shaping tags

### ISSUE THREAD

**Issue by StevanWhite** [wspr/fontspec#132]
Hi!
An issue regarding OpenType features recently came up in XeTeX, but it seems it's a fontspec problem.

It has to do with the 2005 change of Indic script tags, and changes regarding the specifications. 
A bunch of scripts got new tags.  They are the ones marked "v.2" here
    Script tags: http://www.microsoft.com/typography/otspec150/scripttags.htm

It's not clear what the best solution is.  Properly, first it should be checked if the font's feature is to be activated
with the new tag.  If so, use that one, otherwise, check if the font's feature is activated with the old tag.

I found that simply changing the old tags to the new ones in the xelatex fontspec.sty file fixed my immediate problems.

Cheers!

**Comment by wspr** [comment]
Apologies, this one slipped through the cracks!
