### ISSUE TITLE
KOMA-Script -classes work badly with fontspec of XeLaTeX

### ISSUE THREAD

**Issue by juhtolv** [wspr/fontspec#135]
Please check out this bugreport:                                                
                                                                                
http://bugs.debian.org/678079                                                   
                                                                                
Should I really create a minimal example file for you? Have ever even tested KOMA-Script -classes with XeLaTeX and fontspec?

**Comment by wspr** [comment]
I'm going to close this without an example that's minimal enough for me to quickly try. Hopefully the bug has been fixed in the mean time.
