### ISSUE TITLE
Remove xdv2pdf references in the documentation

### ISSUE THREAD

**Issue by wspr** [wspr/fontspec#150]
xdv2pdf is gone as of TL'13.

**Comment by josephwright** [comment]
Is this still open: I don't see `xdv2pdf` in the docs!

**Comment by wspr** [comment]
Hmm, good point. I'll close for now; despite no explicit reference there *could* be a section or two that gets mentions a feature that implicitly requires it. E.g. upcoming commit dc54b6863e39 removes an example that uses "Weight=2" for a Mac font.
