### ISSUE TITLE
testing for font features

### ISSUE THREAD

**Issue by rdtennent** [wspr/fontspec#163]
At tex.stackexchange, I've been advised that the following code will allow me to test  for the presence or activation of font features:

``` tex
\ExplSyntaxOn
\cs_new_eq:NN \IfFontFeatureExists \fontspec_if_feature:nTF
\cs_new:Npn \mico_fontfeature_if_active:nTF #1
  { \tl_if_in:NnTF \l_fontspec_rawfeatures_sclist { #1 } }
\cs_new_eq:NN \IfFontFeatureActive \mico_fontfeature_if_active:nTF
\ExplSyntaxOff 
```

`\IfFontFeatureExists` works fine but  `\IfFontFeatureActive` doesn't,  due I'm told to a bug in fontspec.  If not a bug, please advise on how to test whether font features are currently active.

**Comment by wspr** [comment]
This is a really tricky one because which features are active can depend on the current font size! I would be inclined to suggest that querying the raw OpenType feature tag would be far, far easier:

```
\documentclass{article}
\usepackage{fontspec}
\begin{document}

\ExplSyntaxOn
\def\FeatureActive#1{%
  \exp_args:Nxx \tl_if_in:nnTF
    { \fontname\font } { \tl_to_str:n {+#1} }
    {T} {F}%
}
\ExplSyntaxOff

\fontspec{texgyrepagella-regular.otf}
abc123
\FeatureActive{onum}

\fontspec{texgyrepagella-regular.otf}[Numbers=OldStyle]
abc123
\FeatureActive{onum}

\end{document}
```

**Comment by wspr** [comment]
Ah, this turned out to be rather fun to implement. In the next version a new command `\IfFeatureExistsTF` will be provided for a nice interface for testing if a font has certain features.
