### ISSUE TITLE
LaTeX warning: "xparse/redefine-command" -- I don't care :)

### ISSUE THREAD

**Issue by kberry** [wspr/fontspec#183]
Hi Will - On every run, fontspec wants to inform me:

LaTeX warning: "xparse/redefine-command"
Redefining document command \oldstylenums with arg. spec. 'm' on line 128.

So what :)?  Can this be relegated to the log file where it belongs, please? Thanks.

**Comment by josephwright** [comment]
This is really an `xparse` thing: STATUS BYDESIGN :-)

**Comment by wspr** [comment]
On 4 Mar 2015, at 11:49 pm, Joseph Wright <notifications@github.com> wrote:
> 
> This is really an xparse thing: STATUS BYDESIGN :-)

I thought we decided to send these warnings to the log file?
From some internal discussions last year:

> On 21 Jul 2014, at 4:13 pm, Mittelbach, Frank <frank.mittelbach@latex-project.org> wrote:
> 
> On 20.07.2014 21:07, Joseph Wright wrote:
>> Standard LaTeX2e warnings do go to the terminal, but we could for the
>> moment drop this down to 'info' which will then be log-only. In a 'pure
>> LaTeX3' context we are likely to have to think a bit more about this
>> anyway: presumable a class (or whatever we end up with) can alter
>> semantics so would be fine doing \RenewDocumentCommand, but after
>> loading a class that should be treated differently.
> 
> let's drop to info for now

Did this not happen in the end?

**Comment by josephwright** [comment]
I'll sort this at the `xparse` end later today (we get continued reports about `xparse` being a bit too vocal for most people!).
