### ISSUE TITLE
cannot-use-pdftex

### ISSUE THREAD

**Issue by digitalvapor** [wspr/fontspec#186]
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec.sty:41: Fatal fontspec error: "cannot-use-pdftex"
! 
! The fontspec package requires either XeTeX or LuaTeX to function.
! 
! You must change your typesetting engine to, e.g., "xelatex" or "lualatex"
! instead of plain "latex" or "pdflatex".
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.41  }
       
|'''''''''''''''''''''''''''''''''''''''''''''''
| This is a fatal error: LaTeX will abort
|...............................................
```

Hi, do you have any tips for using the fontspec package with [latexmk](http://www.ctan.org/pkg/latexmk/)?

I've tried using the `%!TEX TS-program = xelatex` line at the top of the file.

I can currently successfully compile using `xetex mydoc.tex` from commandline, I just wanted to use the [atom latex](https://atom.io/packages/latex) package to compile (which invokes `latexmk`), or automate some builds with sharelatex.com.

**Comment by khaledhosny** [comment]
That is really a question for latexmk, nothing for fontspec to do here.
