### ISSUE TITLE
Footnote symbols don't show correctly using \thanks{} and fontspec 

### ISSUE THREAD

**Issue by Cadwallon** [wspr/fontspec#188]
Using xelatex and fontspec.sty as provided by the TexLive 2014 distribution to use custom opentype fonts in latex documents. 

Writing a document of three authors and using the command \thanks{} in the \title or \author fields, all the authors' thanks are just yielded as the last one's: Double-dagger.
 
Further Reference: 
http://latex-community.org/forum/viewtopic.php?f=40&t=5308&sid=a11a0c8c34ca0c06cbe38e5b71d071e2#p84991

**Comment by frederikaalund** [comment]
As a workaround, you can `\usepackage{footmisc}`. That fixed the issue for me. Of course, it would be nice to have a real solution.

**Comment by Cadwallon** [comment]
Thank you! This helped for the time being.

Am 27.01.2015 um 12:17 schrieb Frederik Aalund:
