### ISSUE TITLE
Graphite renderer is not in the admissible choices with XeLaTeX

### ISSUE THREAD

**Issue by eg9** [wspr/fontspec#194]
When a font family is defined with `Renderer=Graphite` a spurious warning is issued and the renderer is not chosen. This is due to a bad index number in the code for the option in `fontspec-xetex.sty` (2014/06/21 v2.4a)

    1220 \keys_define:nn {fontspec-renderer}
    1221  {
    1222   Renderer .choice_code:n =
    1223    {
    1224     \int_compare:nTF {\l_keys_choice_int <= 3} {
    1225       \tl_set:Nv \l_fontspec_renderer_tl
    1226         { g_fontspec_renderer_tag_ \l_keys_choice_tl }
    1227      }
    1228      {
    1229       \__fontspec_warning:nx {only-luatex-feature} {Renderer=Full/Basic}
    1230      }
    1231    }
    1232   ,
    1233   Renderer .generate_choices:n = {AAT,ICU,OpenType,Graphite,Full,Basic}
    1234  }

The index of `Graphite` is 4; from interface3 (Feb. 13, 2015)

> Sets ⟨key⟩ to act as a choice key, and defines a series ⟨choices⟩ which are implemented using the ⟨code⟩. Inside ⟨code⟩, \l_keys_choice_tl will be the name of the choice made, and \l_keys_choice_int will be the position of the choice in the list of ⟨choices⟩ (indexed from 1).

**Comment by khaledhosny** [comment]
Should be fixed now.

**Comment by carbeck** [comment]
Sadly, the "broken" version of this file seems to also be what currently ships with Ubuntu 15.04 (vivid).
