### ISSUE TITLE
Redefinition of \@fnsymbol should be fully-expandable, not protected

### ISSUE THREAD

**Issue by pdgessler** [wspr/fontspec#195]
In `fontspec-patches.sty`, a redefinition of `\@fnsymbol` occurs which renders it `\protect`ed:

    \cs_set_protected:cpn {@fnsymbol} #1

This causes footnote symbols on title pages to appear incorrectly when multiple `\thanks{<...>}` are used, as shown in the image below.

![capture](https://cloud.githubusercontent.com/assets/1495628/6482963/6e44d444-c231-11e4-9e5b-b7535d559502.PNG)

Code to reproduce and a proposed fix by Enrico Gregorio are located at the following question (and answer) at TeX Stack Exchange: [Why does `fontspec` interact with the footnote marks of the `\thanks` command?](http://tex.stackexchange.com/q/231258/21344)

**Comment by pdgessler** [comment]
I just realized that a similar issue was previously reported [here](https://github.com/wspr/fontspec/issues/188). Maybe it's a duplicate, but I'll leave mine here for now since it includes a proposed fix. We can merge the threads together if you wish.

**Comment by josephwright** [comment]
This was fixed in https://github.com/wspr/fontspec/commit/8fd3fdc8e24daed3116cada4af5ed5f48e0f6fc4: I guess a release is needed!
