### ISSUE TITLE
Using SizeFeatures in BoldFeatures breaks bold small caps

### ISSUE THREAD

**Issue by zhenlin** [wspr/fontspec#197]
Using `SizeFeatures` in `BoldFeatures` to select an alternate font for small sizes breaks bold small caps, but it works fine for ordinary small caps. In the following example, XeLaTeX (resp. LuaLaTeX) reports that the font shape `EU1/TimesLTStd(0)/bx/sc` (resp. `EU2/TimesLTStd(0)/bx/sc`) is undefined.

    \documentclass[12pt,a4paper]{article}
    
    \usepackage{fontspec}
    
    \setmainfont[%
    UprightFont={* Roman}, 
    UprightFeatures={
      SizeFeatures={
        {Size=10-},
        {Size=-10, Font={Times Ten LT Std Roman}}
      }},
    BoldFont={* Bold},
    BoldFeatures={
      SizeFeatures={
        {Size=10-},
        {Size=-10, Font={Times Ten LT Std Bold}}
      }},
    ]{Times LT Std}
    
    \begin{document}
    \begin{itemize}
    \item \mdseries\scshape Medium
    
    \item \bfseries\scshape Bold
    \end{itemize}
    \end{document}

**Comment by wspr** [comment]
Sorry I wasn't able to get back to you when this was reported. I've been doing some testing on a pre-release version of the package, and I can't replicate this issue; hopefully it's been fixed along the way. Please let me know once the new version comes out (`v2.5`) if you're still seeing problems.

**Comment by zhenlin** [comment]
Thanks for the update.

When can we expect to see version 2.5? I can still reproduce the issue (LuaTeX beta-0.80.0 or XeTeX 0.99992, fontspec 2.4e).

**Comment by wspr** [comment]
Hopefully very soon. Sorry for the inconvenience.

**Comment by zhenlin** [comment]
I updated to `fontspec` 2.5 this morning, but I still have the same issue. 

(Also, `unicode-math` broke, so I had to revert to `fontspec` 2.4e.)

**Comment by wspr** [comment]
Apologies for the instability -- v2.5a is about to be updated to fix the problem with unicode-math. Regarding the original issue, I don’t have the same fonts that you do, so I attempted to reproduce the problem as follows:

```
\documentclass[10pt,a4paper]{article}
\usepackage{fontspec}
\setmainfont{texgyrepagella}[%
  Extension = .otf ,
  UprightFont={*-regular}, 
  UprightFeatures={
    SizeFeatures={
      {Size=10-},
      {Size=-10, Font={texgyreheros-regular}}
    }},
  BoldFont={*-bold},
  BoldFeatures={
    SizeFeatures={
      {Size=10-},
      {Size=-10, Font={texgyreheros-bold}}
    }},
]
\begin{document}
\begin{itemize}
\item \mdseries\scshape Medium
\item \bfseries\scshape Bold
\end{itemize}
\small
\begin{itemize}
\item \mdseries\scshape Medium
\item \bfseries\scshape Bold
\end{itemize}
\end{document}
```

It appears to work for me. Please let me know if I’m not capturing the issue in this example.

**Comment by zhenlin** [comment]
It works with your fonts, even in version 2.4e. After checking the logs (see below) I realised that the issue is probably that Times Ten LT Std Bold does not support small caps – this causes fontspec to generate an incomplete NFSS spec. But that should not affect bold small caps at sizes > 10, right?

```
.................................................
. fontspec info: "defining-font"
. 
. Font family 'TimesLTStd(0)' created for font 'Times LT Std' with options
. [Ligatures=TeX,UprightFont={* Roman},UprightFeatures={ SizeFeatures={
. {Size=10-}, {Size=-10, Font={Times Ten LT Std Roman}} }},BoldFont={*
. Bold},BoldFeatures={ SizeFeatures={ {Size=10-}, {Size=-10, Font={Times Ten
. LT Std Bold}} }}].
. 
. This font family consists of the following shapes:
. 
. * 'normal' with NFSS spec.:
. <10->"Times LT Std
. Roman/OT:script=latn;language=DFLT;mapping=tex-text;"<-10>"Times Ten LT Std
. Roman/OT:script=latn;language=DFLT;mapping=tex-text;"
. 
. * 'small caps' with NFSS spec.:
. <10->"Times LT Std
. Roman/OT:script=latn;language=DFLT;mapping=tex-text;+smcp;"<-10>"Times Ten
. LT Std Roman/OT:script=latn;language=DFLT;mapping=tex-text;+smcp;"
. and font adjustment code:
. 
. 
. * 'bold' with NFSS spec.:
. <10->"Times LT Std
. Bold/OT:script=latn;language=DFLT;mapping=tex-text;"<-10>"Times Ten LT Std
. Bold/OT:script=latn;language=DFLT;mapping=tex-text;"
. 
. * 'bold small caps' with NFSS spec.:
. <10->"Times LT Std
. Bold/OT:script=latn;language=DFLT;mapping=tex-text;+smcp;"
. and font adjustment code:
. 
. 
. * 'italic' with NFSS spec.:
. <->"Times LT Std Roman/I/OT:script=latn;language=DFLT;mapping=tex-text;"
. 
. * 'small caps' with NFSS spec.:
. 
. and font adjustment code:
. 
. 
. * 'bold italic' with NFSS spec.:
. <->"Times LT Std Bold/I/OT:script=latn;language=DFLT;mapping=tex-text;"
. 
. * 'bold small caps' with NFSS spec.:
. 
. and font adjustment code:
. 
.................................................
```

**Comment by wspr** [comment]
Sorry to have closed the issue early. I'll upload v2.5a of fontspec now and try to look problem later tonight...

**Comment by wspr** [comment]
Ah, you’re totally correct. Apologies again. I see what the problem is, I just need to figure out how to fix it with a minimal amount of code :)

**Comment by wspr** [comment]
Okay, the next commit will fix this. There's not really a good solution to this sort of thing, where a single optical size is missing small caps — running this example results in `LaTeX Error: Font EU1/TimesLTStd(0)/bx/sc/9 not found`:

```
\documentclass[10pt,a4paper]{article}
\usepackage{fontspec}
\setmainfont{TimesLTStd}[ Extension = .otf ,
  UprightFont={*-Roman}, 
  UprightFeatures={
    SizeFeatures={ {Size=10-},
      {Size=-10, Font={TimesTenLTStd-Roman}}
    }},
  BoldFont={*-Bold},
  BoldFeatures={
    SizeFeatures={ {Size=10-},
      {Size=-10, Font={TimesTenLTStd-Bold}}
    }},
]
\begin{document}
\begin{itemize}
\item \mdseries medium {\scshape Medium}
\item \bfseries bold {\scshape Bold}
\end{itemize}
\small
\begin{itemize}
\item \mdseries medium {\scshape Medium}
\item \bfseries bold {\scshape Bold}
\end{itemize}
\end{document}
```

**Comment by zhenlin** [comment]
That seems to have worked. Thanks! I apologise for not making a more detailed report in the first instance.

**Comment by wspr** [comment]
No problem, great that it’s finally fixed — sorry it took me so long `:)`
