### ISSUE TITLE
Error when using fontspec

### ISSUE THREAD

**Issue by Cescfangs** [wspr/fontspec#204]
using a basic version of MacTex, when building `tex` file on sublime, i got:
```
Errors:
/usr/local/texlive/2015basic/texmf-dist/tex/latex/fontspec/fontspec.sty:43: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! [ }]
```

my tex file:
```latex
\documentclass{article}
\usepackage{fontspec}  

\title{Title}
\author{me}

\begin{document}

\maketitle{}

\section{Introduction}

This is where you will write your content. 


\end{document}
```

**Comment by wspr** [comment]
Is there more of an error message you can provide?

Fontspec has recently been updated; you might want to try upgrading to the latest version if you haven't already.

**Comment by davidcarlisle** [comment]
The row of `!!!` makes me suspect you are seeing a truncated message, the full text of which is

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Fatal fontspec error: "cannot-use-pdftex"
! 
! The fontspec package requires either XeTeX or LuaTeX to function.
! 
! You must change your typesetting engine to, e.g., "xelatex" or "lualatex"
! instead of plain "latex" or "pdflatex".
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
```

in which case, the problem is that you are using pdflatex (or latex) rather than xelatex or lualatex.

**Comment by Cescfangs** [comment]
I think you are right about truncated message, in fact,  line 41 in `fontspec.sty` is ` \msg_fatal:nn {fontspec} {cannot-use-pdftex}`.
However, I've changed the typesetting engine from
`pdflatex = ["pdflatex", "-interaction=nonstopmode", "-synctex=1"]`
to
`pdflatex = ["xelatex", "-interaction=nonstopmode", "-synctex=1"]`
in sublme latex building file already.

**Comment by Cescfangs** [comment]
pressed the wrong button, sorry...

**Comment by davidcarlisle** [comment]
If fontspec thinks it's running under pdflatex then my guess is that it is, I know nothing about sublime but can you check the first line of the log file from your document

It should say (modulo version/time differences)

```
This is XeTeX, Version 3.14159265-2.6-0.99991 (TeX Live 2014) (preloaded format=xelatex 2014.7.15)  29 JUL 2015 14:58
```

not

```
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014) (preloaded format=pdflatex 2015.1
```

**Comment by Cescfangs** [comment]
you are right, again.
the first line of the log file says:
```
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015) (preloaded format=pdflatex 2015.7.29)  29 JUL 2015 21:24
```
so I guess it's a sublime issue rather than fontspec?

**Comment by wspr** [comment]
> so I guess it's a sublime issue rather than fontspec?
> 
Definitely not a fontspec issue (in this case).

**Comment by Cescfangs** [comment]
I've figured it out in sublime building file, not a fontspec issue indeed

**Comment by totuta** [comment]
Hi @Cescfangs,

I'm having the same issue here. How did you solve it?

**Comment by Cescfangs** [comment]
@totuta I'am really sorry for the late reply, no matter what you use(Sublime Text for me) to build tex when involving  fontspec, always be sure you use **XeTeX** or **lualatex** instead of "latex" or "pdflatex", for me, I simply modified building settings in Sublime and restart.

**Comment by skmohammadi** [comment]
hi. how can i change typesetting engine from Pdflatex to Xetex on linux?

**Comment by tayyebi** [comment]
Hi. Use `preferences` (or anything on your editor) to set the `Default Compiler` to your choice.

**Comment by littlemeywupp** [comment]
> Hi. Use `preferences` (or anything on your editor) to set the `Default Compiler` to your choice.

Hi, I have set from PdfLaTex to XeLaText in 'Default Compiler', but it still didn't solve the problem and then I checked the first line of the log file from my document which is 'This is pdfTeX...' instead of 'This is XeTeX...'
