### ISSUE TITLE
font interferences leads to lua error "attempt to index field 'shared' (a nil value)"

### ISSUE THREAD

**Issue by u-fischer** [wspr/fontspec#208]
I had the mathgifg package installed (https://www.ctan.org/pkg/mathgifg). This packages contains tfm, vf and afm files to use the georgia fonts with pdflatex. It doesn't contain real fonts.

This had the side effect that a document which tried to use the system font Georgia failed if one doesn't explicitly set the extension:

```
\documentclass[]{article}
\usepackage{fontspec}
%works:
%\setmainfont{Georgia}[Extension=.ttf]
%fails:
\setmainfont{Georgia} 
%fails:
%\setmainfont{Georgia.ttf} 
\begin{document}
abc
\end{document}
```

```
! LuaTeX error ...exmf-dist/tex/luatex/luaotfload/luaotfload-auxiliary.lua:530: 
attempt to index field 'shared' (a nil value)
stack traceback:
    ...exmf-dist/tex/luatex/luaotfload/luaotfload-auxiliary.lua:530: in function 'c
heck_feature'
    ./fontspec.lua:65: in function 'check_ot_feat'
    [\directlua]:1: in main chunk.
\fontspec_check_ot_feat:nTF ...tspec_script_tl ")}
                                                  \if@tempswa \prg_return_tr...
```

Loading the font with luaotfload alone \font\test=Georgia simply tried to use the type1 font (that I don't have) and so failed with a much more understable error message.

**Comment by wspr** [comment]
Thanks Ulrike — I'm wondering if there's much I can do here though. As mentioned in another issue, I've just updated the code that deals with extension processing, so this will hopefully address the failing case with `\setmainfont{Georgia.ttf}`. In the hope that's the case, I'll close this issue now but let me know of any further developments.
