### ISSUE TITLE
SlantedFont affects Smallcaps

### ISSUE THREAD

**Issue by u-fischer** [wspr/fontspec#209]
When I set the slanted font explicitly to a font which has the smcp feature then the upright small caps is affected:

~~~~~
\documentclass{article}

\RequirePackage{fontspec}
\setmainfont{Erewhon}[
    Extension=.otf,
    SlantedFont=*-RegularSlanted, %bad, has smcp feature
    %SlantedFont=*-Bold, %Bad, has smcp feature
    %SlantedFont=*-BoldItalic, %ok, has no smcp feature
    UprightFont=*-Regular,
        ]

\begin{document}
Exercise \textsc{Exercise}
\end{document}
~~~~~~

![slanted](https://cloud.githubusercontent.com/assets/4047173/9197937/b390582c-4038-11e5-816a-2644b2ffda07.PNG)

The log-file then says:

~~~~~
. 
. * 'small caps' with NFSS spec.:
. 
. <->"[Erewhon-RegularSlanted.otf]:mode=node;script=latn;language=DFLT;+tlig;+trep;+smcp;"
~~~~~

Tested with xelatex and lualatex. 

~~~~~
(d:/texlive/2015/texmf-dist/tex/latex/fontspec/fontspec.sty
Package: fontspec 2015/07/22 v2.4d Font selection for XeLaTeX and LuaLaTeX
~~~~~

It doesn't help to add `UprightFeatures= {SmallCapsFont={*-Regular}, SmallCapsFeatures={Letters=SmallCaps} },`

**Comment by wspr** [comment]
Apologies! I appear to have a couple of related issues surrounding this.
I'll try and take a look ASAP…

**Comment by wspr** [comment]
I'm sorry not to get around to this earlier, Ulrike! This turned out to be relatively obvious — while we "trick" the NFSS to get small caps italics, I currently haven't done the same thing for slanted small caps. I guess I should.
