### ISSUE TITLE
Fullwidth letters are not displayed in math mode.

### ISSUE THREAD

**Issue by bpump** [wspr/fontspec#212]
Hello,

Fullwidth letters (e.g. U+FF3A) are displayed in text mode but as soon as they're placed inside \begin{equation} environment they disappear. It would've been great if you could make all the Unicode characters supported by the font to be displayed in math mode as well.

Thanks

**Comment by wspr** [comment]
Thanks for reporting this, but it's not fontspec's responsibility. It could be done in unicode-math, for sure, but what would the behaviour be? U+FF3A produces the same output as typing ascii "Z", which produces U+1D44D in the output?

**Comment by wspr** [comment]
Continue discussion here: <https://github.com/wspr/unicode-math/issues/337>
