### ISSUE TITLE
addfontfeatures-ignored no info

### ISSUE THREAD

**Issue by kberry** [wspr/fontspec#219]
hi will,

i just got this warning from fontspec:

* fontspec warning: "addfontfeatures-ignored"
*
* \addfontfeature(s) ignored; it cannot be used with a font that wasn't
* selected by fontspec.

sorry to say it, but ... how frustrating! dozens of fonts are being loaded in nefarious and indirect ways by the complex document i'm running (which i didn't write).  

so ... what font? what features? obviously fontspec knows what it's being asked to do, so how about telling poor me, too? at least give me the \inputlineno. am i missing it? i see nothing in either the .log or the online output.

i realize it's more work, but in general, i believe that every diagnostic should be accompanied with the specifics of the call in question ...

thanks,
karl

**Comment by wspr** [comment]
Hi Karl,
Good point!!
I'll see what I can do :-)

**Comment by wspr** [comment]
For now I've updated the message in fontspec, but we're discussing whether expl3-based warnings should show this information by default (we're thinking it should). Update coming soon.
