### ISSUE TITLE
Linux Libertine can not be loaded by filename

### ISSUE THREAD

**Issue by u-fischer** [wspr/fontspec#220]
The following document fails with TL2015 + lualatex:

```
\documentclass{article}
\usepackage{fontspec}
%\DeclareFontsExtensions{.ttf,.OTF,.TTF,.ttc,.TTC,.dfont} %work around
% works
%\setmainfont{LinLibertine_R}[Extension=.otf]
%\setmainfont{texgyrepagella-regular.otf}
% setmainfont{LinLibertine_RI.otf}

%fails
\setmainfont{LinLibertine_R.otf}

\begin{document}
blb
\end{document} 
```

I get the error

```
! LuaTeX error ...ad-texmf/tex/luatex/luaotfload/fontloader-fontloader.lua:5869:
 font loading failed.
<to be read again> 
\scan_stop: 
l.11 \setmainfont{LinLibertine_R.otf}
```

The issue has been discussed on the luaotfload site and we found out is that the cause is that fontspec removes the extension .otf and then through kpsewhich `LinLibertine_R.tex` is found and loaded as font. 

https://github.com/lualatex/luaotfload/issues/269

I'm not sure if anything can be done to avoid the problem. Probably one simply has to load the font always with `\setmainfont{LinLibertine_R}[Extension=.otf]`.

**Comment by davidcarlisle** [comment]
Not sure that it helps but the example document worked for me, on
investigation I think because of

/c/Windows/Fonts/LinLibertine_R.otf

ie the file's in the system font directory as well as the texlive tree.

**Comment by u-fischer** [comment]
You could try to force the problem by moving LinLibertine_R.tex in the current directory.

**Comment by wspr** [comment]
This is all pretty weird. Why does luaotfload try to load the `.tex` file as a font? The extension stripping is only done for a certain step of the processing, so I'll try to make it more robust.

**Comment by wspr** [comment]
The extension stripping code has been altered recently; I'm going to close this now but please let me know if you see anything further.
