### ISSUE TITLE
Ligatures=NoTeX

### ISSUE THREAD

**Issue by wspr** [wspr/fontspec#221]
This is easy in LuaTeX but not sure about XeTeX at present.

**Comment by wspr** [comment]
This will be happening in the next release.

**Comment by timothymctim** [comment]
Was this actually implemented in a newer version? I’m using version 2.6, but it doesn’t work with this version. As an alternative I’m currently using `RawFeature=-tlig`.
I also have to related issues (please let me know if I should open a separate issue):
1. Using `Ligatures=TeXReset` and `Ligatures=ResetAll` gives me an `Argument of \__fontspec_swap_plus_minus_aux:Nq has an extra }.` error. (I understood (from #82) that `Reset` was modified around the same time the issue should have been addressed.)
2. The documentation is confusing to me. The [`features` environment](https://github.com/wspr/fontspec/blob/master/fontspec-doc-style.sty#L249) states that “options can be disabled with `..Off` variants.” However, (at least for Ligatures) the options should be disabled with `No..` variants, right?

**Comment by timothymctim** [comment]
Ah, sorry, I see in your revision history that you’ve probably already fixed the issue with `Reset` in v2.6a.
