### ISSUE TITLE
Commit 6a85cac breaks working class file with  "The font size command \normalsize is not defined"

### ISSUE THREAD

**Issue by pmagwene** [wspr/fontspec#229]
Please see my comment on commit 6a85cac here:

https://github.com/wspr/fontspec/commit/6a85cac3f95ed09c7af412742402d7b3be4f33be

**Comment by wspr** [comment]
Strange if that slipped through the test suite; are you loading fontspec before `\documentclass` by any chance?

**Comment by pmagwene** [comment]
Indeed.   In my custom document class that derives from letter. `\RequirePackage{fontspec}` called was coming before the `\LoadClass{letter}`. When I swap the order, and restore the commit, all is fine.

**Comment by wspr** [comment]
Thanks for the confirmation — I'll add a fix to only call `\normalsize` if it's needed, then. I won't be able to do this straight away, however…

**Comment by pmagwene** [comment]
Thanks. It's easy enough to work around in the meantime. Cheers!

**Comment by vitaminace33** [comment]
I had the exact same problem. I was defining a class based on `letter`. If `\RequirePackage{fontspec}` goes prior `\LoadClass{letter}`, it triggers the error
```
! LaTeX Error: The font size command \normalsize is not defined:
               there is probably something wrong with the class file.
```
I don't know if @wspr fixed the issue, if this is a recurring bug, nor if it even needs to be fixed.

In [_LaTeX 2ε for class and package writers_, page 13](https://osl.ugr.es/CTAN/macros/latex/base/clsguide.pdf), it is stated that `\normalsize`, `\textwidth`, `\textheight` and `\pagenumbering` need to be set by the class. This is taken care of by `letter` but not before it is loaded, therefore one can simply set its values at an earlier stage. As suggested in the aforementioned reference:
```
\renewcommand{\normalsize}{\fontsize{10pt}{12pt}\selectfont}
\setlength{\textwidth}{6.5in}
\setlength{\textheight}{8in}
\pagenumbering{arabic}
```
