### ISSUE TITLE
unexpected result of tex.sprint() in verbatim env.

### ISSUE THREAD

**Issue by dohyunkim** [wspr/fontspec#230]
I get a bunch of unexpected `\FontspecSetCheckBoolTrue`s in the pdf with the MWE compiled with lualatex:
```tex
\documentclass{article}
\usepackage{polyglossia}
\setmainfont{DejaVuSerif.ttf}
\setmonofont{DejaVuSansMono.ttf}
\setdefaultlanguage{greek}
\begin{document}
α \verb|α|
\end{document}
```
because `tex.sprint()` in fontspec.lua currently does not have optional parameter denoting a catcode table.  Everything is ok with the code around line 30 in fontspec.lua being changed into the following:
```lua
local latex = luatexbase.registernumber("catcodetable@latex")
local function tempswatrue()  tex.sprint(latex,[[\FontspecSetCheckBoolTrue ]]) end
local function tempswafalse() tex.sprint(latex,[[\FontspecSetCheckBoolFalse]]) end
```

**Comment by wspr** [comment]
Oops, apologies! If you could put together a pull request I'm happy to accept it directly. Many thanks

**Comment by Lenchik** [comment]
Seems like this issue also causes `! LaTeX Error: Something's wrong--perhaps a missing \item.` error when using `Verbatim` environment from [`fancyvrb`](http://www.ctan.org/pkg/fancyvrb) package (similarly while non-english languages set in preamble). Reverting to 2.4e version of fontspec helps.
