### ISSUE TITLE
Incorrect italic 'Book' weights chosen

### ISSUE THREAD

**Issue by adunning** [wspr/fontspec#233]
With the [following document](https://github.com/wspr/fontspec/files/173663/test.pdf), fontspec uses the Book weight of Gill Sans MT Pro for non-italicized text, and Medium Italic for the italics:

```tex
\documentclass{minimal}
\usepackage{fontspec}
\defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
    \setmainfont{Gill Sans MT Pro}

\begin{document}

This is a \emph{test}.

\end{document}
```

It works if one uses:

```tex
\setmainfont
  [Ligatures=TeX,
   UprightFont={* Book},
   ItalicFont={* Book Italic}]
  {Gill Sans MT Pro}
```

These are the weights included in the font:

- Light
- Light Italic
- Book
- Book Italic
- Medium
- Medium Italic
- Bold
- Bold Italic
- Heavy
- Heavy Italic
- Extra Bold
- Condensed
- Bold Condensed
- Ultra Bold Condensed
- Display Bold
- Display Extra Bold
- Display Bold Condensed
- Bold Extra Condensed

**Comment by wspr** [comment]
Thanks for writing. Unfortunately `fontspec` has nothing to do with the "auto-selection" of shapes and weights and has no way to influence the results -- for complex fonts such as this one there is often confusion by the engine to guess which is the correct one. Generally you're expected to be specific in such situations, using the syntax you give in the issue. I use `.fontspec` files to automate the selection of specific families within a superfamily like this.

**Comment by adunning** [comment]
I am clearly spoiled by your cleverness in dealing with optical sizes. Thanks!

**Comment by wspr** [comment]
Actually a lot of that is also just the engine being clever :) The extra features in fontspec only override what XeTeX or luaotfload do by default!
