### ISSUE TITLE
Recent update does not work with LaTeX doc package

### ISSUE THREAD

**Issue by zhouyan** [wspr/fontspec#234]
After update to latest `fontspec` through TeXLive 2015, documentations for my own packages started to show some wired artifacts. I am able to reproduce the problem with the following minimal working example.

Driver file:

```
\documentclass{article}
\usepackage{fontspec}
\usepackage{doc}
\setsansfont{Calibri}

\CodelineNumbered
\DeclareDocumentCommand\theCodelineNo{}{
  {\normalfont\sffamily\addfontfeatures{Numbers=OldStyle}
    \scriptsize\arabic{CodelineNo}}
}

\begin{document}
\DocInput{test.dx}

\end{document}
```

`test.dtx`

```
%    \begin{macrocode}
Some code
%    \end{macrocode}
```

It works fine with XeLaTeX. However, if compiled with LuaLaTeX, the results has some extra strings. I attached it in `test.pdf`.

It might be issues in `fontspec.lua` line 29 and 30 where `tempswatrue` and tempswafalse` used `tex.sprint`. It seems to me that the commands `\FontspecSetCheckBoolTrue` and `\FontspecSetCheckBoolFalse` was inserted inside a verbatim environment and got output. I am not familiar with the internals of the `doc` package or LuaTeX. My best guess is we need `tet.cprint` to insert the string with correct catcode regardless where it might be called.

[test.pdf](https://github.com/wspr/fontspec/files/174887/test.pdf)

**Comment by wspr** [comment]
Ah, this has already been fixed in the source on Github but I have been too busy to prepare a release for CTAN. Apologies for the inconvenience; I hope to be able to do this later in the week.

**Comment by zhouyan** [comment]
Thanks. There's no hurry anyway. It does not break anything other than doc as far as I know
