### ISSUE TITLE
Problems with small caps and certain fonts

### ISSUE THREAD

**Issue by simifilm** [wspr/fontspec#239]
The following MWE breaks with TL16 pretest and `luaotfload` 2.7 and `fontspec`:

```
\documentclass{article}
\usepackage{fontspec}
\setmainfont{LibreBaskerville-Regular.otf}
\begin{document}
\textsc{Zeitgeist}
 \end{document}
```

This seems to be a problem of `fontspec` since the following example works with `plain luatex` (though I have to confess that I know very little about `plain luatex`):

```
 \input luaotfload.sty\relax
    \font\x="file:LibreBaskerville-Regular.otf:+smcp;mode=base;+tlig" at 10pt\relax
    \x abc
    \bye
```

**Comment by wspr** [comment]
Thanks for the report. What error message is given? I can try to reproduce. Do the fonts that break have anything in common? (All definitely do have small caps, for example?)

**Comment by simifilm** [comment]
Here is the error message:

```
LaTeX Font Warning: Font shape `EU2/LibreBaskerville-Regular.otf(0)/m/sc' undefi
ned
(Font)              using `EU2/LibreBaskerville-Regular.otf(0)/m/n' instead on i
nput line 9.

.
\@outputpage ...or \hb@xt@ \textwidth {\@thefoot }
                                                  \color@endbox }}\global \l...
l.10  \end{document}
                  
? 
```


This font does not have small caps, but this should not lead to LaTeX stop the current run. At least, it did not in the past.

In general, there seem to be quite a lot of problems with TL16 pretest and `luaotfload` 2.7. Most of my fonts which are not part of TL seem to have problems.

**Comment by schlcht** [comment]
Probably this: https://github.com/lualatex/luaotfload/issues/340

(I get the error message `attempt to index upvalue 'parameters' (a nil value)`, but only on the console, not in the log file)

**Comment by simifilm** [comment]
With the latest fixes to `luaotfload` my original MWE seems to work again.

**Comment by wspr** [comment]
Great, glad to hear it :) I'll close this for now but let me know if anything crops up again.
