### ISSUE TITLE
fontspec fails with fonts accompanying tfm

### ISSUE THREAD

**Issue by aminophen** [wspr/fontspec#240]
I reported this in [luaotfload issue](https://github.com/lualatex/luaotfload/issues/338), but this might be fontspec issue, so I'll copy from it.

Following code compiles correctly with LuaTeX beta-0.80.0 + luaotfload v2.6 (= TL2015 frozen), but fails with LuaTeX beta-0.95.0 + luaotfload v2.7 (= TL2016 pretest).
~~~~ tex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{cmtt10}
\begin{document}
Hello, \LaTeX!
\end{document}
~~~~
~~~~
luaotfload | resolve : step 1: apply method "tex" (function: 0x7fa3e561b920)
luaotfload | resolve : 1: method "tex" indicated lookup success
luaotfload | resolve : method "tex" resolved "cmtt10" -> cmtt10 (cmtt10.tfm)...exmf-dist/tex/luat
ex/luaotfload/luaotfload-auxiliary.lua:333: attempt to index field 'metadata' (a nil value)
stack traceback:
	...exmf-dist/tex/luatex/luaotfload/luaotfload-auxiliary.lua:333: in function '
provides_script'
	/usr/local/texlive/2016/texmf-dist/tex/latex/fontspec/fontspec.lua:32: in func
tion 'check_ot_script'
	[\directlua]:1: in main chunk.
\fontspec_check_script:nTF ...ontspec_font","#1")}
                                                  \bool_if:NTF \l__fontspec_...

l.3 \setmainfont{cmtt10}
~~~~
Any suggestions?

**Comment by wspr** [comment]
Hmm, I'll have to investigate further... I don't think fontspec has ever been tested or recommended for loading tfm fonts like this.

**Comment by u-fischer** [comment]
It was a luaotfload problem (at least the error message), Philip just committed a change https://github.com/lualatex/luaotfload/issues/338.
