### ISSUE TITLE
Incompatibility `NFSSFamily` and `\addfontfeature`

### ISSUE THREAD

**Issue by sergey-s-betke** [wspr/fontspec#242]
Source code:

```
    \setmainfont
      { \tl_use:N \c_@@_mainfont_tl }
      [
        NFSSFamily = \tl_use:N \c_@@_NFSSFamily_tl,
        \tl_use:N \g_@@_font_features_tl
      ]
```

When later in document I write `\addfontfeature`

```
    { \addfontfeature{Language=German} No.}
```

result - zero. Just if I set `NFSSFamily`.

My suggestion: `\addfontfeature` must ignore `NFSSFamily` in current font.

Thank You for Your answer!

**Comment by wspr** [comment]
Hmm, I guess there might well be an interaction here that I didn’t take into account. Can you put together a minimal example using standard fonts that shows the problem?

**Comment by wspr** [comment]
The following example works for me:

```
\newfontfamily\myfamily{texgyrepagella-regular.otf}[
  NFSSFamily = foo ,
]

\fontfamily{foo}\selectfont
hello

\addfontfeature{Colour=990000}
hello
```

I'll close this now but do let me know if I've misunderstood.

**Comment by sergey-s-betke** [comment]
Excuse me, I need time for testing...
