### ISSUE TITLE
`feature file` functionality apparently vanished with luaotfload 2.7 --- update docs ?

### ISSUE THREAD

**Issue by jfbu** [wspr/fontspec#243]
I can't find immediately a link, but when https://github.com/lualatex/luaotfload/releases/tag/v2.7 was released I remember reading somewhere that font forge libraries were dropped, and the handling of "feature files" too (<strike>as the user doc for `luaotfload` does not seem to list changes, I can only offer this vague formulation</strike> see NEWS file in luaotfload distribution, which however is not incorporated in PDF user documentation).

Anyway, using https://github.com/lualatex/luaotfload/releases/tag/v2.7-fix-1 I could again test with this

```latex
\documentclass{article}

\usepackage{fontspec}

\setmainfont{Vollkorn}[%
% un chemin absolu ne semble pas marcher
%    FeatureFile={/Users/xxxxxx/Library/Fonts/vollkornlua.fff},
% ceci ne marche pas si vollkornlua.fff est dans mon ~/Library/texmf
    FeatureFile={vollkornlua.fff},
    RawFeature={+oneb},
    UprightFont={* -Regular},
    ItalicFont={* -Italic}, 
    BoldFont={* -Bold}, 
    BoldItalicFont={* -BoldItalic},
    Extension={.otf}]

\begin{document}

1234567890

\bfseries 1234567890

\itshape 1234567890

\mdseries 1234567890

\end{document}

% Local Variables:
% TeX-engine: luatex
% End:
```

and directory containing file `vollkornlua.fff` 

```
languagesystem DFLT dflt;
languagesystem latn dflt;

# Lundi 14 décembre 2015 à 16:08:58
# pour utilisation par LuaLaTeX.
feature oneb {
  sub one by one.ss01;
} oneb;


```
and indeed I don't get the access to the stylistic variant for the digit `1`.

I report it here because LaTeX user will use `fontspec` and its doc currently says nothing about this.

Or I am wrong, and this is an altogether other problem ?

**Comment by jfbu** [comment]
cross posting https://github.com/lualatex/luaotfload/issues/347

**Comment by jfbu** [comment]
It is confirmed that TeXLive 2016 LuaTeX+luaotfload will have no support for font feature files. Thus fontspec's manual should presumably be purged of references to this.

**Comment by jfbu** [comment]
Fortunately it is possible to move the contents of the font feature file directly into a Lua call to an otf font handler as explained by @dohyunkim there https://github.com/lualatex/luaotfload/issues/347#issuecomment-215625928

**Comment by jfbu** [comment]
:+1:

**Comment by floriandk** [comment]
Do you think you could push this update to CTAN? As `luatex` itself doesn't give any error-messages about the removed feature, it is very difficult to find out, what is wrong when following `fontspec`'s manual doesn't yield the expected results...

**Comment by wspr** [comment]
Sorry, expect a big update in the next couple of days...
