### ISSUE TITLE
Numbers option has no influence in small caps with certain fonts

### ISSUE THREAD

**Issue by simifilm** [wspr/fontspec#244]
Consider the following MWE:

> \documentclass{article}
> \usepackage{fontspec}
> \setromanfont[
> Ligatures = {TeX},
> Numbers=OldStyle,
> SmallCapsFeatures={Numbers=OldStyle}]
> {Palatino Linotype}
> \begin{document}
> 1234 \textsc{1234}
>  \end{document}

Using `TL16 pretest`, `fontspec` and `luaotfload` 2.7-fix-1 I get the following:
![MWE](http://www.simifilm.ch/images/linotypeexample.jpg)

As you can see, the `Numbers` option has no influence on the numbers in small caps. I can't influence the small caps numbers at all and the numbers used are neither neither oldstyle nor lining but something which looks like a superscript font. In fact, no option seems to change anything about the small caps, `Letters=Uppercase` does not seem to do anything either.

I am not sure wether this is a problem of the font or of `fontspec` (or `luaotfload`), but obviously, oldstyle numbers do exist in the font but they are not accessed in small caps.

I realize that this example is far from perfect since it relies on a proprietary font, but if needed, I can provide the font for test reasons.

**Comment by wspr** [comment]
Thanks for filing the bug. That looks strange indeed. Can you try with a plain LuaLaTeX example? The syntax would be something like

    \documentclass{article}
    \usepackage{luaotfload}
    \begin{document}
    \font\x="file:texgyrepagella-regular.otf"\relax
    \x abc1234 % "default"
    \font\x="file:texgyrepagella-regular.otf:+smcp;+onum"\relax
    \x abc1234 % small caps
    \font\x="file:texgyrepagella-regular.otf:+smcp;+lnum"\relax
    \x abc1234 % small caps + lining
    \font\x="file:texgyrepagella-regular.otf:+smcp;+onum"\relax
    \x abc1234 % small caps + old-style
    \end{document}

(Also note that `\setromanfont` has been deprecated for many years; `\setmainfont` is the “new” command to use.)

**Comment by simifilm** [comment]
This 
```    \documentclass{article}
    \usepackage{luaotfload}
    \begin{document}
    \font\x="file:PalatinoLinotype.ttf"\relax
    \x abc1234 % "default"
    \font\x="file:PalatinoLinotype.ttf:+smcp;+onum"\relax
    \x abc1234 % small caps
    \font\x="file:PalatinoLinotype.ttf:+smcp;+lnum"\relax
    \x abc1234 % small caps + lining
    \font\x="file:PalatinoLinotype.ttf:+smcp;+onum"\relax
    \x abc1234 % small caps + old-style
    \end{document}
```
gives me this:

![MWE](http://www.simifilm.ch/images/palatinolua.jpg)

So there seems to be something fishy with this font. When I use it in InDesing, the OpenType feature small caps seems also to use this small numbers. I can only use activate the oldstyle numbers, when I deactivate small caps.

So while this seems to be at least partly a problem of the font, I still wonder whether it is possible to somehow force the oldstyle numbers for small caps. After all, the glyphs do exist.

**Comment by wspr** [comment]
It would at least be worth reporting to luaotfload's issue tracker in case it's not a font problem.
