### ISSUE TITLE
confusion about xunicode loading and whether tuenc is default

### ISSUE THREAD

**Issue by jfbu** [wspr/fontspec#245]
The doc says:

> A new package option, tuenc, which is selected by default, ... As a result, with this package option, Ross Moore’s xunicode package is not loaded.

But if I compile simple document with LuaLaTeX the log has 

```
(/usr/lo
cal/texlive/2016/texmf-dist/tex/xelatex/xunicode/xunicode.sty
File: xunicode.sty 2011/09/09 v0.981 provides access to latin accents and many o
ther characters in Unicode lower plane
```

which is loaded via 

```
(/usr/local/texlive/2016/texmf-dist/tex/latex/fontspec/fontspec-luatex.sty
Package: fontspec-luatex 2016/02/01 v2.5a Font selection for XeLaTeX and LuaLaTe
X
```

I am checking the doc as in current TL2016 pretest, not the one for the current master on repo, but the commits since v2.5a tag do not seem to indicate relevant changes, and fontspec-opening.dtx from the repo has the `\RequirePackage{xunicode}`.

It appears that  `euenc` option is executed but the doc seems to say that `tuenc` is default.

**Comment by wspr** [comment]
Apologies for the confusion — I fully intended to make `tuenc` the default before now, but life got in the way. Now that we’re so close to the end of the pretest, I dare not make such a radical change, but hope to release a new version of fontspec shortly after TL2016 is official to “switch over” to the new encoding.

**Comment by wspr** [comment]
TU is now being incorporated in to the LaTeX2e kernel, and for TL2017 TU will be the default in fontspec. We're planning a synchronised release shortly to allow time for testing.
