### ISSUE TITLE
Emphasis not rendered recursively

### ISSUE THREAD

**Issue by adunning** [wspr/fontspec#246]
Using the latest fontspec and LuaLaTeX or XeLaTeX, emphasis does not render within a footnote, as in the following example:

```tex
\documentclass{article}

\usepackage{fontspec}

\begin{document}

This is a \emph{test\footnote{\emph{test}} of emphasis}.

\end{document}
```

It works as expected if one removes the `\usepackage{fontspec}` line.

**Comment by jfbu** [comment]
After I looked a bit at the fontspec modification of  ``\em`` I tried the following

 ```latex
\documentclass{article}

\usepackage{fontspec}

\begin{document}

\section{\textit{a \emph{test} of emphasis}}

\end{document}
```

and the inner emphasis does not render (it should be upright) with lualatex/xelatex contrarily to pdftex (without fontspec)

**Comment by jfbu** [comment]
in my previous comment you can spare the ``\section``,

for some reason I forget I was looking at some table of contents example initially,

anyway ``\textit{a \emph{test} of emphasis}`` behaves differently with or without fontspec

**Comment by eg9** [comment]
`fontspec` changes the implementation of `\em` and `\emph`, see section 6 in the manual, subsection **Emphasis and nested emphasis**.

There is a shortcoming that should be solved by `fontspec` itself; you can temporarily fix it by redefining `\reset@font`:

    \documentclass{article}
    \usepackage{fontspec}

    \ExplSyntaxOn
    \cs_set:cpn { reset@font } { \normalfont \int_zero:N \l__fontspec_em_int }
    \ExplSyntaxOff

    \setlength{\textheight}{2cm} % just for the example

    \begin{document}

    This is a \emph{test\footnote{\emph{test}} of emphasis}.

    \end{document}

<img width="307" alt="screen shot 2016-07-05 at 16 13 39" src="https://cloud.githubusercontent.com/assets/302839/16587637/e177f452-42cb-11e6-8499-42555d498ec5.png">

**Comment by wspr** [comment]
Thanks Enrico! This has been fixed in the source. Not promises for a new release soon though.

**Comment by eg9** [comment]
A public interface for resetting the `\em` level would also be welcome, see http://tex.stackexchange.com/questions/318374/

**Comment by wspr** [comment]
I should have realised that there would be lots of cases where people would want `\textit{\emph{...}}` (or equiv.) to do something sensible. Maybe I should explicitly check for that case in the redefinition of `\em`.

When you say a public interface to redefine the `\em` level, would you imagine something like

    `\fontspec_set_em_level:n {1}`

or

    `\EmLevel{1}`

or ... ? (Maybe best to reply with a new issue number `:)` )

**Comment by eg9** [comment]
Since `\l__fontspec_em_int` is “private”, but it seems to be needed also in user's contexts, a public interface such as `\fontspec_set_em_level:n {1}` should be sufficient; a higher level interface can be easily built upon this. I just hate using private variables at the top level so making Frank unhappy. `;-)`

**Comment by Lenchik** [comment]
> Not promises for a new release soon though.
Maybe some bugfix 2.5b release with just existing commits added? Just for fixing already found bugs.

**Comment by wspr** [comment]
Some pretty big updates in this area in commit #8c4306ccb82d54853e730f546f0bdab4167574af. `\fontspec_set_em_level:n` is provided (although not officially documented yet), but more importantly it should be much more robust to manual font changes.
