### ISSUE TITLE
hyperref link colouring stopped working with TL2016

### ISSUE THREAD

**Issue by c-alpha** [wspr/fontspec#247]
Since I upgraded to TL2016, hyperref links are no longer rendered in a different colour if the default font is assigned any non-default colour.

In the MWE below, links are coloured blue as intended. If the commented line (just after `\usepackage{fontspec}` is activated to render the text in dark-grey colour, the links lose the blue colour and appear in the same colour as the other text.

```latex
\documentclass{report}

\usepackage[table,hyperref]{xcolor}
\definecolorset{RGB}{}{}{dark-grey,50,48,46;link-blue,0,0,153}
\globalcolorstrue

\usepackage{fontspec}
% \defaultfontfeatures{Color=dark-grey}	%%% uncomment this line and the links will no longer be blue
\setmainfont{Helvetica Neue Light}[BoldFont={Helvetica Neue Bold},ItalicFont={* Italic}]

\usepackage{hyperref}
\hypersetup{%
  linktoc=all,%
  linkcolor=link-blue,%
  urlcolor=link-blue,%
  colorlinks=true,%
}

\begin{document}
\section{The First section}
\label{sec:first-section}
This is some text that we will refer to using the \href{https://github.com/ho-tex/hyperref}{hyperref package}.

\section{The Second Section}
\label{sec:second-section}
This is more text in the second section. The important stuff has been said in \autoref{sec:first-section} already.

\end{document}
```

Configuration: Tex Live 2016 (last update today), compiling with XeLaTeX, Mac OS X 10.11.5

**Comment by eg9** [comment]
I'm not sure what you mean about “no longer”, because the color is also lost with TL 2012, as far as I can see.

**Comment by c-alpha** [comment]
> I'm not sure what you mean about “no longer”, because the color is also lost with TL 2012, as far as I can see.

I can confirm that it yielded my desired effect (text dark grey, links blue) with TL'14 and '15. Maybe it was a bug in those releases and should never have worked in the first place?

> You can try the workaround in http://tex.stackexchange.com/a/22061/4427 which consists in adding
> [...]

This works like a charm in the MWE, and sans `\makeatletter` and `\makeatother` in the document class I'm using.  Many thanks for the hint and pointer!

Just for curiosity: What would speak against including the `\def\HyColor...` line in fontspec itself?

**Comment by eg9** [comment]
@c-alpha 

I tested it and always got grey. Anyway, the fix to `\Hy@color@@@@UseColor` should better be done in `hyperref`

**Comment by c-alpha** [comment]
Many thanks for your swift and kind support! I'll suggest the update to the hyperref maintainer.

**Comment by c-alpha** [comment]
I did some more checking, and it turns out that the fix you suggested allows `fontspec` and `hyperref` to coexist, but other packages (in my case `listings`) were still prevented from rendering text in different colours. I would have needed a similar kludge for each and every other package that wants to change the text colour.

As I mentioned, the issue only shows when I set the main font colour using `fontspec`. https://tex.stackexchange.com/questions/28305/how-do-i-get-fontspec-to-work-with-text-color-white-in-xelatex#29409 suggests a way of setting the default font colour independent of `fontspec` (or any other package for that matter). If I use that solution, `hyperref`, `listings`, and other packages are able to render text in different colours, while maintaining the desired, non-default main font colour.

It seems the way that `fontspec` sets the main font colour makes coexistence with other packages less easy?

**Comment by davidcarlisle** [comment]
The accepted answer in that stackexchange link doesn't use font colour
attributes at all, it just uses classic (x)color package whatsit nodes.
(which is also how hyperref colours links) so it avoids the question of
whether font colour wins over the currently specified document color which
is the issue here.

 color package whatsit nodes colour TeX text and rules that have no natural
colour but they have no effect on the colour of coloured images and
arguably it is correct that they have no effect on font specified colours.

**Comment by c-alpha** [comment]
Thanks @davidcarlisle for your swift response. I am much less of a TeX monk that you appear to be, so please accept my apologies if I'm showing off my lack of understanding (and please don't hesitate to let me know when I do).

> The accepted answer in that stackexchange link doesn't use font colour attributes at all, it just uses classic (x)color package whatsit nodes. (which is also how hyperref colours links) so it avoids the question of whether font colour wins over the currently specified document color which is the issue here.
> [...]

To me it seems that Philippe Goutet's comment on https://tex.stackexchange.com/questions/26549/how-do-i-globally-set-the-text-color-in-xelatex/26560#26560 (which is referenced from the Stack Exchange answer I quoted) says basically the same thing, i.e. that due to the way that the main text colour is set by `fontspec`, it is mutually exclusive with those other packages which are not designed to be used with`fontspec` and which render parts of the text in different colour?

The reasons may well be intrinsic to the ways text colour is handled and thus beyond the control of any package author?

This aspect of `fontspec`'s behaviour is long standing, hence it would not not seem advisable to me to change such a basic thing. I believe it could be helpful however to add a clarifying statement to section 8.1 of the `fontspec` documentation along the lines of Philippe Goutet's comment mentioned above to tell users that using the `Color` font specification may prevent other packages such as e.g. `hyperref` or `listings`from rendering coloured text:

> I would only use the Color font feature if I really wanted all the colors specified in the document to be overwritten (e.g. to convert a document to black and white, pictures non-withstanding). Otherwise, redefining LaTeX's \default@color is much more natural, doesn't interfere with \color or \textcolor and works whatever the engine or the document class.
> **-- Philippe Goutet / Aug 26 '11 at 18:38**
_(quote from https://tex.stackexchange.com/questions/26549/how-do-i-globally-set-the-text-color-in-xelatex/26560#26560)_
