### ISSUE TITLE
Specify font index numbers of TTC fonts

### ISSUE THREAD

**Issue by zr-tex8r** [wspr/fontspec#248]
With the fontspec package users can specify fonts by files names instead of font names. However, when using a font in TrueType Collection (TTC) format, they need to specify an font index number together with the file name.

XeTeX’s `\font` primitive supports specification of index numbers.

```tex
% use index 1 of ASANA.TTC
\font\sample="[ASANA.TTC:1]:+onum"
\sample fontspec v2.5a
```

Then it will be nice if fontspec also supports this functionality.

```tex
% use index 1 of ASANA.TTC
\fontspec{ASANA.TTC}[FontIndex=1,Numbers=OldStyle]
fontspec v2.5a
```

Note: As for LuaTeX (luaotfload), I’ve heard that this functionality is currently in development.

**Comment by phi-gamma** [comment]
2016-10-25 (Tuesday), notifications@github.com (Takayuki YATO):

> With the fontspec package users can specify fonts by files
> names instead of font names. However, when using a font in
> TrueType Collection (TTC) format, they need to specify an font
> index number together with the file name.
> 
> XeTeX’s `\font` primitive supports specification of index numbers.
> 
>     ```tex
>     % use index 1 of ASANA.TTC
>     \font\sample="[ASANA.TTC:1]:+onum"
>     \sample fontspec v2.5a
>     ```
> 
> Then it will be nice if fontspec also supports this functionality.
> 
>     ```tex
>     \fontspec{ASANA.TTC}[Numbers=OldStyle]
>     fontspec v2.5a
>     ```
> 
> Note: As for LuaTeX (luaotfload), I’ve heard that this functionality is currently in development.

Luaotfload:

    \font \f = file:ASANA.TTC(1):+onum

Best,
Philipp

**Comment by zr-tex8r** [comment]
Sorry, there was an error in my previous post.
Now I have fixed it.

>   Then it will be nice if fontspec also supports this functionality.
>   
>   ```tex
>   % use index 1 of ASANA.TTC
>   \fontspec{ASANA.TTC}[FontIndex=1,Numbers=OldStyle]
>   fontspec v2.5a
>   ```

My intention is to propose the `FontIndex` option, possibly with a more suitable name.

**Comment by wspr** [comment]
Thanks all, I'll *try* to get something ready over the next few weeks…
