### ISSUE TITLE
support ornament feature (+ornm)

### ISSUE THREAD

**Issue by eroux** [wspr/fontspec#249]
Arno Pro contains some glyphs accessible only through the `+ornm=X` where `X` is an integer from 0 to 56. It would be very useful to have an option `Ornament=X` in fontspec, as it's currently impossible to set it through RawFeature due to the limitation of the `xkeyval` syntax. For instance

```tex
\fontspec{Arno Pro}[RawFeature=+ornm=0]
```

gives

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! LaTeX error: "kernel/misplaced-equals-sign"
! 
! Misplaced equals sign in key-value input 5
! 
! See the LaTeX3 documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
```

**Comment by eg9** [comment]
I don't have Arno Pro; does

    \fontspec{Arno Pro}[RawFeature={+ornm=0}]

work?

**Comment by eroux** [comment]
Ooooooooooooh it works indeed, thanks a lot! Well, I still think it would be useful to have it in fontspect natively, but at least it's not blocking

**Comment by eg9** [comment]
I support the feature request, of course.

**Comment by eroux** [comment]
Thanks!
