### ISSUE TITLE
\emph is broken

### ISSUE THREAD

**Issue by simifilm** [wspr/fontspec#254]
I just updated to `fontspec` 2.5c, and with this version `\emph{}` is undefined. With the following MWE `\textit{}` gives correct italics, while `\emph{}` does nothing:

```
\documentclass{article}
\usepackage{fontspec}
\setmainfont{texgyrepagella-regular.otf}[
       BoldFont       = texgyrepagella-bold.otf ,
       ItalicFont     = texgyrepagella-italic.otf ,
       BoldItalicFont = texgyrepagella-bolditalic.otf ]
\begin{document}\textit{Lala}\emph{Lala}
\end{document}
```

**Comment by wspr** [comment]
Ah, how embarrassing!
You can fix it in fontspec-(xetex|luatex).sty with:

```
\cs_generate_variant:Nn \prop_gput:Nnn  {NxV}
+\cs_generate_variant:Nn \prop_gput_if_new:Nnn  {NxV}

-          \prop_gput:NxV \g_@@_em_prop { \f@series/\f@shape } { \l_@@_emdef_int }
+          \prop_gput_if_new:NxV \g_@@_em_prop { \f@series/\f@shape } { \l_@@_emdef_int }
```

I’ll send an update to CTAN shortly.

**Comment by wspr** [comment]
Update to fix this now sent to CTAN.

**Comment by crmackay** [comment]
any idea when this might show up on CTAN for download via `tlmgr`?

**Comment by wspr** [comment]
I see it’s now in CTAN so should be in TL Real Soon now (if not already).

**Comment by crmackay** [comment]
Sounds good. Thanks for the great work!
