### ISSUE TITLE
tuenc fails to use some symbols that are present in the font

### ISSUE THREAD

**Issue by chrisjbillington** [wspr/fontspec#256]
I had a document that was rendering with the 2016 release of fontspec, using lualatex, and I'm now rendering it with the 2017 release which has tuenc default. I noticed some symbols were not rendering correctly. Here is a MWE:

```
\documentclass{report}
\usepackage[euenc]{fontspec}
\setmainfont{GaramondPremrPro}
\usepackage{microtype}
\begin{document}
\textless \{Hello, na\"ive world! \`i \'i \^i \} \textgreater \textbackslash
\end{document}

```

This works fine, and gives the following:

![tex_correct](https://cloud.githubusercontent.com/assets/1044087/22277502/1115c7c6-e28a-11e6-88e5-821449274fde.png)

but if [euenc] option is omitted, then none of the accented characters render (they just come out as normal "i" characters), and the greater than, less than, backslash and braces all fall back to computer modern or something:

![tex_incorrect](https://cloud.githubusercontent.com/assets/1044087/22277489/e27f7b96-e289-11e6-8684-06ec07ffafc4.png)

microtype is unnecessary, but it coughs warnings about all the symbols that are affected - this example includes all of them, so perhaps these are the only characters in this font for which it's a problem.

I can of course replace my umluated ï with a unicode character, and not use \textgreater etc, using the characters themselves "<" and ">" work correctly. But I'm not sure about braces or slashes. Anyway, although I can get the outcome I want, I'd like to know if this is a bug, or if not, what's the kosher way to get these characters rendering properly without relying on "euenc", since it seems like it is deprecated and there for backward compatibility only.

Using the font Minion results in the exact same problem, with microtype complaining about the same set of characters.

Here is the full output of lualatex for the case where euenc is omitted:

http://pastebin.com/rBPA9JDJ

**Comment by chrisjbillington** [comment]
It's possible that the bug is not with fontspec but with some other component of lualatex, because fontspec was obviously not the only thing that changed when I started using texlive 2016 instead of 2015. 

So more specifically:

The example renders correctly regardless of whether tuenc or euenc is set with fontspec 2.5a, in LuaTeX, Version beta-0.80.0 (TeX Live 2015) (rev 5238).

The incorrect rendering happens with tuenc set (by default or explicitly) with fontspec 2.5c in LuaTeX, Version 0.95.0 (TeX Live 2016). But it renders correctly if euenc is set.

**Comment by wspr** [comment]
Thanks for the report, much appreciated. I definitely wouldn't have expected the output you're providing — and while you're right that tuenc.def is provided by LaTeX2e from 2017, I will chase it up there. I can reproduce the problem with the symbols, but for me the accents are turning up okay. But I'm not using a vanilla TeX Live installation so I'll try again tonight.

**Comment by davidcarlisle** [comment]
On 25 January 2017 at 04:51, Will Robertson <notifications@github.com>
wrote:

> Thanks for the report, much appreciated. I definitely wouldn't have
> expected the output you're providing — and while you're right that
> tuenc.def is provided by LaTeX2e from 2017, I will chase it up there. I can
> reproduce the problem with the symbols, but for me the accents are turning
> up okay. But I'm not using a vanilla TeX Live installation so I'll try
> again tonight.
>
>
>
I think if you add the lines from the diff below it shoul dwork, the new
tuenc is declaring composites with
\i (only) not i so  \'\i woul dwork.

Normally that means you get an accent over the dotted is but presumably in
this font (which I don't have to check)
the accent characters are not there so you are just getting i.
we can add this in the base latex update.

$ diff tuenc.def~ tuenc.def
251a252
> \DeclareTextComposite{\`}             \UnicodeEncodingName{i}{"00EC}
252a254
> \DeclareTextComposite{\'}             \UnicodeEncodingName{i}{"00ED}
253a256
> \DeclareTextComposite{\^}             \UnicodeEncodingName{i}{"00EE}
254a258
> \DeclareTextComposite{\"}             \UnicodeEncodingName{i}{"00EF}
304a309
> \DeclareTextComposite{\~}             \UnicodeEncodingName{i}{"0129}
306a312
> \DeclareTextComposite{\=}             \UnicodeEncodingName{i}{"012B}
308a315
> \DeclareTextComposite{\u}             \UnicodeEncodingName{i}{"012D}
310a318
> \DeclareTextComposite{\k}             \UnicodeEncodingName{i}{"012F}
378a387
> \DeclareTextComposite{\v}             \UnicodeEncodingName{i}{"01D0}

**Comment by chrisjbillington** [comment]
Ah, I see.

Yes, that fixes the accents for me, and the other characters are fixed by adding:

```
\DeclareTextSymbol{\textbackslash}       \UnicodeEncodingName{"005C}
\DeclareTextSymbol{\textless}            \UnicodeEncodingName{"003C}
\DeclareTextSymbol{\textgreater}         \UnicodeEncodingName{"003E}
\DeclareTextSymbol{\textbraceleft}       \UnicodeEncodingName{"007B}
\DeclareTextSymbol{\textbraceright}      \UnicodeEncodingName{"007D}
```

**Comment by davidcarlisle** [comment]
Yes sorry I should have mentioned the others, we'd already added those and
so I didn't notice that they were not in the public version yet (I should
have noticed, as I only added them the day before...)

There have been some other fixes, the current version (between `<*TU>` and
`</TU>` is in svn at

https://www.latex-project.org//svnroot/latex2e-public/trunk/base/ltoutenc.dtx

We will do a latex update to get this to ctan today or tomorrow most likely.

**Comment by chrisjbillington** [comment]
Excellent, thank you!

The same changes in tuenc.def should be made with the "j" composites as with the "i" ones, right? They seem to suffer the same problem, despite microtype not complaining about them.

**Comment by davidcarlisle** [comment]
Yes I added j versions of the composites declared for \j (just \^ and \v)
they should be in the version in ltoutenc.dtx that linked to before.

**Comment by wspr** [comment]
Thanks all — I'll close this now but please let me know if you have further troubles.
