### ISSUE TITLE
Something wrong with lualatex font path on Windows with fontspec 2.5d

### ISSUE THREAD

**Issue by LSinev** [wspr/fontspec#262]
This `Path` thing worked with lualatex on Windows with fontspec 2.5a
```tex
        \setmonofont{cour}[ % Courier New
            Script = Latin,
            Path = c:/windows/fonts/,
            Extension = .ttf,
            UprightFont = *,
            BoldFont = *bd,
            ItalicFont = *i,
            BoldItalicFont = *bi]
        \newfontfamily\cyrillicfonttt{cour}[ % Courier New
            Script = Cyrillic,
            Path = c:/windows/fonts/,
            Extension = .ttf,
            UprightFont = *,
            BoldFont = *bd,
            ItalicFont = *i,
            BoldItalicFont = *bi]
```
But with 2.5d it causes `file not found` errors. Switching back to 2.5a backup version restores errorless behaviour.

**Comment by davidcarlisle** [comment]
Possibly the same issue as

http://tex.stackexchange.com/q/350883/1090

**Comment by davidcarlisle** [comment]
@LSinev  I haven't a windows texlive to check but in view of the comments on that stackexchange question, doe sit work if you use /window/fonts (when you are on the C drive) not as a real fix but to see if it's same issue.

**Comment by LSinev** [comment]
Yes it works.

**Comment by wspr** [comment]
Can you please try with plain font selection syntax? Something like
```
\documentclass{article}
\usepackage{luaotfload}
\begin{document}
\font\1=[c:/windows/fonts/cour.ttf] at 10pt\1 hello
\end{document}
```
If this fails then it's not fontspec's fault — although if the problem persists I could intercept `C:` and remove it from the path string. (Doesn't help people with fonts on, say, `D:` though.)

**Comment by davidcarlisle** [comment]
note a new luatotfload went to ctan today so worth trying with that before changing fontspec

**Comment by LSinev** [comment]
This test passes, though without new luaotfload:
```
This is LuaTeX, Version 0.95.0 (TeX Live 2016/W32TeX)  (format=lualatex 2017.1.29)  30 JAN 2017 07:34
 system commands enabled.
**test-font-sel.tex
(./test-font-sel.tex
LaTeX2e <2017/01/01> patch level 1
Lua module: luaotfload-main 2016/06/16 2.70003 OpenType layout system.
Lua module: lualibs 2016-04-06 2.4 ConTeXt Lua standard libraries.
Lua module: lualibs-extended 2016-04-06 2.4 ConTeXt Lua libraries -- extended co
llection.
luaotfload | conf : Root cache directory is C:/texlive/2016/texmf-var/luatex-cac
he/generic/names.
luaotfload | init : Loading fontloader “fontloader-2016-06-16.lua” from kpse
-resolved path “c:/texlive/2016/texmf-dist/tex/luatex/luaotfload/fontloader-20
16-06-16.lua”.
```

**Comment by phi-gamma** [comment]
2017-01-29 (Sunday), notifications@github.com (LSinev):

> This test passes, though without new luaotfload:
> ```
> This is LuaTeX, Version 0.95.0 (TeX Live 2016/W32TeX)  (format=lualatex 2017.1.29)  30 JAN 2017 07:34
>  system commands enabled.
> **test-font-sel.tex
> (./test-font-sel.tex
> LaTeX2e <2017/01/01> patch level 1
> Lua module: luaotfload-main 2016/06/16 2.70003 OpenType layout system.
> Lua module: lualibs 2016-04-06 2.4 ConTeXt Lua standard libraries.
> Lua module: lualibs-extended 2016-04-06 2.4 ConTeXt Lua libraries -- extended co
> llection.
> luaotfload | conf : Root cache directory is C:/texlive/2016/texmf-var/luatex-cac
> he/generic/names.
> luaotfload | init : Loading fontloader “fontloader-2016-06-16.lua” from kpse
> -resolved path “c:/texlive/2016/texmf-dist/tex/luatex/luaotfload/fontloader-20
> 16-06-16.lua”.

You can get more information about what ends up being passed to
Luaotfload by creating a file ``luaotfload.conf`` in the local
directory containing these lines:

    [run]
       definer = info_patch

See also https://github.com/phi-gamma/luaotfload/blob/master/doc/luaotfload.conf.rst#section-run

Best,
Philipp

**Comment by LSinev** [comment]
tested 2.5a, 2.5d (with two variants of path) and plain example with this `luaotfload.conf`. tex and log files in zip attached
[fontspec_and_luaotfload_test.zip](https://github.com/wspr/fontspec/files/738443/fontspec_and_luaotfload_test.zip)

**Comment by phi-gamma** [comment]
2017-01-30 (Monday), notifications@github.com (LSinev):

> tested 2.5a, 2.5d (with two variants of path) and plain example with this `luaotfload.conf`. tex and log files in zip attached
> [fontspec_and_luaotfload_test.zip](https://github.com/wspr/fontspec/files/738443/fontspec_and_luaotfload_test.zip)

2.5a gets it right:

    471 luaotfload | loaders :    > spec "[c:/windows/fonts/cour.ttf]"
    484 luaotfload | loaders :    > spec "[c:/windows/fonts/courbd.ttf]"
    503 luaotfload | loaders :    > spec "[c:/windows/fonts/couri.ttf]"
    522 luaotfload | loaders :    > spec "[c:/windows/fonts/courbi.ttf]"

Currently there is no way around this syntax if you wish to use
absolute paths with Luaotfload.

2.5d does something different:

     392 luaotfload | loaders :    > spec "file:c:/windows/fonts/cour.ttf"
     521 luaotfload | loaders :    > spec "file:c:/windows/fonts/courbd.ttf"
     592 luaotfload | loaders :    > spec "file:c:/windows/fonts/couri.ttf"
     663 luaotfload | loaders :    > spec "file:c:/windows/fonts/courbi.ttf"

This can’t work with Windows drive letters because the definition
syntax reserves the colon character as delimiter for historical
reasons. https://github.com/lualatex/luaotfload/blob/master/doc/luaotfload-main.tex#L185

Looks like an intentional change. We could make this work on the
Luaotfload end, I believe, by requiring that file names always be
at least two characters long (reasonable but not 100 % backward
compatible). Or add a separate ``path:`` lookup with a different
syntax. I’m open for suggestions.

**Comment by LSinev** [comment]
> 2.5d does something different
Why can't it do the same way as did 2.5a? `luaotfload` wasn't changed during these tests.

**Comment by wspr** [comment]
Hi all — there's no harm in going back to the [..] syntax; I had a mistaken thought that it was preferred. Thanks for spotting the problem!
