### ISSUE TITLE
\emph failed with \bfseries

### ISSUE THREAD

**Issue by louisstuart96** [wspr/fontspec#263]
Perhaps it's better to leave out the `\f@series` macro in `\g_@@_em_prop`?
BTW, the new mechanism makes `\em` behave different from LaTeX2e kernel's version if used with `\slshape` (well, I wonder which is right):
```
\documentclass[a4paper,10pt]{article}
\begin{document}
\slshape Test \emph{emphasized text level 1 with \emph{level 2 with \emph{level 3}}}.
% kernel version: level 1 & 3 is \upshape, level 2 is \itshape
% fontspec version: level 1 & 3 is \itshape, level 2 is \upshape
\end{document}
```

**Comment by louisstuart96** [comment]
hotfix for \slshape problem:
```
\prop_gput:Nnn \g__fontspec_em_prop {m/sl} {1}
```

**Comment by wspr** [comment]
Hmm, I guess I should have called the new version \Emph to avoid breaking everyone's documents!!

**Comment by wspr** [comment]
Can you post an example of what's breaking with bfseries? The logic of the new `\emph` command is to look up whether the current series+shape is on the "emph scale", and if not apply the first level of emphasis. So if there's nothing listed for a particular series it should just start from the beginning.

Unless I'm mistaken the following example works correctly?

```
\documentclass[a4paper,10pt]{article}
\usepackage{fontspec}
\begin{document}
{test \emph{test \bfseries \emph{test}}}\par
{\bfseries test \emph{test \emph{test}}}
\end{document}
```

**Comment by louisstuart96** [comment]
MWE:
```
\documentclass[a4paper,10pt]{article}
\usepackage{fontspec}

\begin{document}

{\bfseries Test \emph{emphasized level 1 with \emph{level 2 with \emph{level 3}}}.}

\end{document}
```
Well, this problem happens when \em is nested deeper than 2 levels. Because series / shape combinations like `bx/it` or `b/it` are not registered in `g_@@_em_prop`, the second level of \em uses \emreset instead of \eminnershape.

**Comment by wspr** [comment]
Ah, sorry I missed this earlier. You’re right of course.
While I could drop the idea of having series and shape together as part of \emph, what do you think about defaulting to something like the following?

    \emfontdeclare{ \emshape, \eminnershape, \upshape \bfseries, \emshape, \eminnershape }

I’m not sure if I’m overcomplicating matters here :)

This still doesn’t work if someone wants to define multiple levels of boldness (\fontseries{sb}, for example). I.e., the changes could still some documents.

Regardless of where I go with that, I think I have to change the name of \emph to \Emph just for sanity’s sake.

**Comment by louisstuart96** [comment]
Registering `\f@shape` alone in `\g_@@_em_prop` would be fine:
```
\documentclass[a4paper,10pt]{article}
\usepackage{fontspec}
\setmainfont{TeX Gyre Termes}

\ExplSyntaxOn\makeatletter
\cs_set_protected:Npn \emfontdeclare #1
  {
    \prop_clear:N \g__fontspec_em_prop
    \int_zero:N   \l__fontspec_emdef_int
    \group_begin:
      \normalfont
      \clist_map_inline:nn {\emreset,#1}
        {
          ##1
          \prop_gput_if_new:NxV \g__fontspec_em_prop { \f@shape } { \l__fontspec_emdef_int }
          \prop_gput:Nxn \g__fontspec_em_prop { switch-\int_use:N \l__fontspec_emdef_int } { ##1 }
          \int_incr:N \l__fontspec_emdef_int
        }
    \group_end:
  }
\DeclareRobustCommand \em
  {
    \@nomath\em

    \prop_get:NxNT \g__fontspec_em_prop { \f@shape } \l__fontspec_em_tmp_tl
      { \int_set:Nn \l__fontspec_em_int { \l__fontspec_em_tmp_tl } }

    \int_incr:N \l__fontspec_em_int

    \prop_get:NxNTF \g__fontspec_em_prop { switch-\int_use:N \l__fontspec_em_int } \l__fontspec_em_switch_tl
      { \l__fontspec_em_switch_tl }
      {
        \int_zero:N \l__fontspec_em_int
        \emreset
      }

  }
\ExplSyntaxOff\makeatother
\emfontdeclare{\emshape, \eminnershape}

\begin{document}

Test \emph{emphasized level 1 with \emph{level 2 with \emph{level 3 }}}.

{\bfseries Test \emph{emphasized level 1 with \emph{level 2 with \emph{level 3 }}}.}

\end{document}
```

**Comment by wspr** [comment]
Yes, that definitely works and it probably what I’ll move to. The reason I didn’t do that originally, though, was to allow people to — for example — use boldness as part of emphasis if they like.

I now think there’s too much compromise with that idea so I’ll add a separate feature to support that if really desired.

Thanks for looking into the code in such a detailed way!

**Comment by davidcarlisle** [comment]
> Regardless of where I go with that, I think I have to change the name of
\emph to \Emph just for sanity’s sake.

I don't think anyone will want both in the same document.
How about instead having a command or package option [classicemph] or some
such that just backs it out goes back to the original \emph for when people
need that compatibility.

**Comment by wspr** [comment]
Yep, something like that :)
