### ISSUE TITLE
Various issues with selecting `pnum`, `onum`, `lnum`, and `tnum` tags.

### ISSUE THREAD

**Issue by zhouyan** [wspr/fontspec#264]
To establish a baseline of discussion, below I first show the correct output of the four possible combinations of number styling, (this, and all the following screenshots were captured at the same scale, so a comparison of the height of `1` is accurate to tell if it is lining or old style)

<img width="324" alt="screen shot 2017-01-30 at 07 02 33" src="https://cloud.githubusercontent.com/assets/538601/22408797/329ed7dc-e6ba-11e6-8ff2-9133b53d69c4.png">

Now, first consider the following minimal example, 

```
\documentclass{article}
\usepackage{fontspec}
\setmainfont{Arno Pro}[Numbers = {OldStyle,Proportional}]
\begin{document}
\fontsize{36}{36}\selectfont
1111
\end{document}

```

And I got the output as below, 
<img width="86" alt="screen shot 2017-01-30 at 07 02 38" src="https://cloud.githubusercontent.com/assets/538601/22408804/6bea4ad0-e6ba-11e6-88b5-11d213a73ab6.png">

That is, the figures are monospaced instead of proportional,

However, if I instead put `Proportional` first, that is, 

```
\setmainfont{Arno Pro}[Numbers = {Proportional,OldStyle}]
```

Then, I get the correct output,

<img width="61" alt="screen shot 2017-01-30 at 07 02 57" src="https://cloud.githubusercontent.com/assets/538601/22408817/a6262cfa-e6ba-11e6-818f-bf362e03f865.png">

Next issue is regarding `RawFeature`. Continuing he above example, consider the following,
```

\documentclass{article}
\usepackage{fontspec}
\setmainfont{Arno Pro}[Numbers = {Proportional,OldStyle}]
\begin{document}
\raggedright
\fontsize{36}{36}\selectfont
{\addfontfeatures{RawFeature=-onum;+lnum}1111}\break
{\addfontfeatures{RawFeature=-lnum;+onum}1111}\break
{\addfontfeatures{RawFeature=-pnum;+tnum}1111}\break
{\addfontfeatures{RawFeature=-tnum;+pnum}1111}\break
\end{document}

```
I get the following output, 
<img width="82" alt="screen shot 2017-01-30 at 07 09 21" src="https://cloud.githubusercontent.com/assets/538601/22408836/0e282614-e6bb-11e6-901a-93cef8d8bd51.png">

That is, the `RawFeatures` have no effects at all. However, if I remove the options in `setmainfont`, that is only plain `setmainfont{Arno Pro}`, then everything works out fine. 

Unfortunately, I cannot produce these issues with a free typeface, though I can reproduce it with quite a few commercial fonts, not only with optical fonts such as Arno but also with some others.

However, I can confirm that none of the issues above happen before recent releases.

The reason that the last issue is particularly troubling is that there's no currently workaround of it I can find. Some commercial fonts, such as a few from Hoelf & Co, defaults to old style figures, but has the `lnum` tag, without an `onum` tag. That is, to switch to lining figure, one can use `Numbers = Lining`, but to switch back, one can only use `-lnum`.  There's no options such as `NoLining`. So I usually defines macros such as

```
\def\txfigures{\addfontfeatures{RawFeature=-lnum;+onum}}
```
which works well pretty much with any fonts (as long as it does have old style figures).

**Comment by wspr** [comment]
Thanks for writing and sorry for the problems you’re having. To address your first issue, the best way to debug these problems is to look in the log file for sections like this:

```
*************************************************
* fontspec warning: "defining-font"
* 
* Font family 'aldus-nova(0)' created for font 'aldus-nova' with options
* [Ligatures=TeX,Extension = .otf,UprightFont = AldusNovaPro-Book,ItalicFont =
* AldusNovaPro-BookItalic,BoldFont = PalatinoNovaPro-Medium,BoldItalicFont =
* PalatinoNovaPro-MediumIt,Numbers={Monospaced,OldStyle}].
*  
*  This font family consists of the following NFSS series/shapes:
*  
* - 'normal' (m/n) with NFSS spec.:
* <->"[AldusNovaPro-Book.otf]/OT:script=latn;language=DFLT;mapping=tex-text;+tn
um;+onum;"
* - 'small caps'  (m/sc) with NFSS spec.:
* <->"[AldusNovaPro-Book.otf]/OT:script=latn;language=DFLT;mapping=tex-text;+tn
um;+onum;+smcp;"
* - 'bold' (bx/n) with NFSS spec.:
* <->"[PalatinoNovaPro-Medium.otf]/OT:script=latn;language=DFLT;mapping=tex-tex
t;+tnum;+onum;"
* - 'bold small caps'  (bx/sc) with NFSS spec.:
* <->"[PalatinoNovaPro-Medium.otf]/OT:script=latn;language=DFLT;mapping=tex-tex
t;+tnum;+onum;+smcp;"
* - 'italic' (m/it) with NFSS spec.:
* <->"[AldusNovaPro-BookItalic.otf]/OT:script=latn;language=DFLT;mapping=tex-te
xt;+tnum;+onum;"
* - 'italic small caps'  (m/itsc) with NFSS spec.:
* <->"[AldusNovaPro-BookItalic.otf]/OT:script=latn;language=DFLT;mapping=tex-te
xt;+tnum;+onum;+smcp;"
* - 'bold italic' (bx/it) with NFSS spec.:
* <->"[PalatinoNovaPro-MediumIt.otf]/OT:script=latn;language=DFLT;mapping=tex-t
ext;+tnum;+onum;"
* - 'bold italic small caps'  (bx/itsc) with NFSS spec.:
* <->"[PalatinoNovaPro-MediumIt.otf]/OT:script=latn;language=DFLT;mapping=tex-t
ext;+tnum;+onum;+smcp;"
*************************************************
```

There you’ll be able to see exactly what OpenType feature is being applied with the fontspec commands.

For the `RawFeature` option not working, the problem was that it was being interpreted too early by fontspec in the processing change, so rather than overriding the defaults, the opposite was happening! Thanks for spotting this.

**Comment by zhouyan** [comment]
Thanks for the quick reply. For the first issue, the following is the output of log file,
```
\setmainfont{Arno Pro}[Numbers = {OldStyle,Proportional}]
```

.```
................................................
. fontspec info: "defining-font"
. 
. Font family 'ArnoPro(0)' created for font 'Arno Pro' with options
. [Ligatures=TeX,Numbers = {OldStyle,Proportional}].
.  
.  This font family consists of the following NFSS series/shapes:
.  
. - 'normal' (m/n) with NFSS spec.:
. <->"ArnoPro:mode=node;script=latn;language=DFLT;+tlig;+onum;"
. - 'small caps'  (m/sc) with NFSS spec.:
. <->"ArnoPro:mode=node;script=latn;language=DFLT;+tlig;+onum;+smcp;"
. - 'bold' (bx/n) with NFSS spec.:
. <->"ArnoPro/B:mode=node;script=latn;language=DFLT;+tlig;+onum;"
. - 'bold small caps'  (bx/sc) with NFSS spec.:
. <->"ArnoPro/B:mode=node;script=latn;language=DFLT;+tlig;+onum;+smcp;"
. - 'italic' (m/it) with NFSS spec.:
. <->"ArnoPro/I:mode=node;script=latn;language=DFLT;+tlig;+onum;"
. - 'italic small caps'  (m/itsc) with NFSS spec.:
. <->"ArnoPro/I:mode=node;script=latn;language=DFLT;+tlig;+onum;+smcp;"
. - 'bold italic' (bx/it) with NFSS spec.:
. <->"ArnoPro/BI:mode=node;script=latn;language=DFLT;+tlig;+onum;"
. - 'bold italic small caps'  (bx/itsc) with NFSS spec.:
. <->"ArnoPro/BI:mode=node;script=latn;language=DFLT;+tlig;+onum;+smcp;"
.................................................

```

It seems that when `Proportional` is specified after `OldStyle`, the `pnum` tag is not used at all. However if I reverse the order of these two, I got,
```
. <->"ArnoPro:mode=node;script=latn;language=DFLT;+tlig;+pnum;+onum;"
```
etc., which is expected.

**Comment by wspr** [comment]
Hmm, you're right; that's weird.

**Comment by zhouyan** [comment]
Just in case it makes a difference, I am using `LuaTeX, Version 0.95.0 (TeX Live 2016)`

**Comment by wspr** [comment]
As a temporary workaround, you can write

    \setmainfont{Arno Pro}[Numbers=OldStyle,Numbers=Proportional]

I can't pin down where this bug is coming from; it's possibly part of the `expl3` keyval processing code (?).

**Comment by zhouyan** [comment]
That's possible. I don't see anything suspicious in fontspec. But I doubt it is an issue with expl3. If it is with the keyval processing, shouldn't we get 'onum' ignored when it's put behind 'Proportional'?

One possible reason is some issues with the font. My version of Arno is pretty old (circa, 2007). The very fact that I cannot reproduce the problem EB Garamond, lead me to think that it can be some issues with the font. I'am planning to purchase a new version of Arno from fontspring anyway. I will wait until I experiment with that.

**Comment by wspr** [comment]
I was able to reproduce the problem with Aldus Nova, so I don’t think it’s the font.
But you’re right that it’s suspicious the order affects the processing.

I haven’t had a chance to investigate further — I'll try to strip the example way down bypassing all sorts of fontspec internals, but it will take me a little time.

(Hopefully I wake up tomorrow and have a light bulb moment, but…)
