### ISSUE TITLE
Command \newopentypefeature not working

### ISSUE THREAD

**Issue by KSundstrom** [wspr/fontspec#266]
The command `\newopentypefeature` seems to have been broken in a recent update. I used it without problem last year (2016), but now, by way of example, get the error

> `! Undefined control sequence.
> \newopentypefeature ...efine_opentype_feature:nnn 
>                                                   {#1}{#2}{#3}
> l.49 \newopentypefeature{Style}{MathGreek}{+mgrk}`

when trying to define a style for mathematical Greek (which e.g. Junicode relies on to some extent).

The exact same error occurs under both XeLaTeX and LuaLaTeX, as well as with other OpenType features not defined by fontspec out-of-the-box (e.g. the example with localized forms in the manual on CTAN).

It seems to be quite possible to work around this using `\newfontfeature` instead, but it stills seems a relevant bug to report.

**Comment by wspr** [comment]
Oh, a complete oversight! Apologies and thanks for the bug report.
