### ISSUE TITLE
ORNM feature example

### ISSUE THREAD

**Issue by zhouyan** [wspr/fontspec#267]
This is not really a bug report.

I was going through the document of the new release to see the new features, and noticed the under 
16.8.5 Ornament — ornm
that a font supporting this feature need to be found. So I went through the free fonts distributed with TeXLive, and find only one such font, `/usr/local/texlive/2016/texmf-dist/fonts/opentype/public/missaali/Missaali-Regular.otf`
A blackletter. Maybe this will be of help.

There are a few commercial fonts also support this feature, such as Arno, Minion, Brioso, and a few other Robert Slimbach designs, among others. Below is an example of the feature applied to Arno's `\textbullet`

```
\documentclass{article}
\usepackage{fontspec}
\usepackage{tikz}
\setmainfont{Arno Pro}

\def\test#1{{\addfontfeatures{Ornament=#1}#1. \textbullet\ }}

\begin{document}
\foreach \x in {0,...,56} {\test{\x}}
\end{document}

```
![screen shot 2017-02-01 at 07 54 37](https://cloud.githubusercontent.com/assets/538601/22489677/d44b2f1e-e853-11e6-87e2-037bfd2ea0b8.png)

**Comment by wspr** [comment]
Thanks! I have been trying to remove commercial fonts from the main documentation to make it more portable, but I’ll look into the `texmf` one. No idea which ornaments it provides? :)

**Comment by wspr** [comment]
I've looked into missaali, and unfortunately its "ornm" feature is a bit obscure. Oh well :) Thanks for the suggestion though!
