### ISSUE TITLE
Feature resets broken

### ISSUE THREAD

**Issue by KSundstrom** [wspr/fontspec#275]
With the latest update the feature reset options (e.g. `Ligatures=ResetAll`, or `Numbers=LowercaseReset`) seem to have been broken. With XeLaTeX (Version 3.14159265-2.6-0.99996 MiKTeX 2.9.6210 NEXT 64-bit) I get the following error:

> `! Argument of \__fontspec_swap_plus_minus_aux:Nq has an extra }.
> <inserted text> 
>                 \par 
> l.42 \setmainfont{Junicode}`

Let me nevertheless thank you for your fantastic work on this package and others!

**Comment by wspr** [comment]
Ah dear. Not enough test files. Thanks — I’ll attempt to fix up tonight/tomorrow.

**Comment by KSundstrom** [comment]
Update 2.6 of 14 Feb 2017, that is. Should have mentioned that for clarity, of course.
