### ISSUE TITLE
Follow proper expl3/xparse guidelines

### ISSUE THREAD

**Issue by wspr** [wspr/fontspec#276]
See egreg's scolding here: http://tex.stackexchange.com/a/354277/179

**Comment by eg9** [comment]
Yes, I just came to GitHub for opening an issue to the purpose and found this. `;-)`

I don't really understand why a user would add code to `\addfontfeatures`, but the problem is independent from this particular application.

**Comment by RobtAll** [comment]
I am the RobtA who raised this on stackexchange.

There is a rational reason for wanting to hack \addfontfeatures. It is the same that applies to \setmainfont and all other fontspec commands.

Current fontspec allows non-OT features such as Color and Opacity, which cannot be controlled by xcolor settings. In a template using xcolor with monochrome or gray, the usual \color and \textcolor commands produce black or grayscale, respectively. But fontspec circumvents this restriction.

In PDF/X for printing to paper, the color model is extremely important. If the user can circumvent the template color model by using fontspec features, that is a problem. So, I hacked fontspec by placing a filter before the features are set. If the user requests Color or Opacity, my code throws an error. This is not best practice, but it is all that is available as I write this.

**Comment by davidcarlisle** [comment]
I'm surprised you need to redefine `\addfontfeatures` to do that, wouldn't
it be simpler just to redefine the color key to do nothing (or give an
error or whatever)?

**Comment by RobtAll** [comment]
David, I didn't "need" to redefine `\addfontfeatures`. Rather, I have low programming skill. That was the first thing I tried, and as long as it worked (which it did, for awhile) I gave it no further thought. Apparently WR is looking at the Color key now.
