### ISSUE TITLE
Fontspec and tipa

### ISSUE THREAD

**Issue by jspitz** [wspr/fontspec#280]
This is probably not really a `fontspec` issue, but I don't know where else to report, and I think you might have some ideas, so I bring it up here.
As of the introduction of the TU encodings (with `fontspec` 2.6), the `xunicode` package is no longer loaded. This also pulls the plug for `tipa` support. A workaround is to use the `euenc` option (with the drawback that the old encodings have to be used) or to load `xunicode` manually (with the `\def\XeTeXpicfile{}` trick if LuaTeX is used), but I wonder

- if there are drawbacks, and which, when loading `xunicode` on top of `tuenc`
- if it has drawbacks to cheat `xunicode` and load it with LuaTeX
- if `xunicode` is now considered 'obsolete'
- whether it would make sense to strip all tipa-related code from xunicode and set up a new package for fontspec-tipa support.

**Comment by davidcarlisle** [comment]
On 21 February 2017 at 08:10, Jürgen Spitzmüller <notifications@github.com>
wrote:

> This is probably not really a fontspec issue, but I don't know where else
> to report, and I think you might have some ideas, so I bring it up here.
> As of the introduction of the TU encodings (with fontspec 2.6), the
> xunicode package is no longer loaded. This also pulls the plug for tipa
> support. A workaround is to use the euenc option (with the drawback that
> the old encodings have to be used) or to load xunicode manually (with the
> \def\XeTeXpicfile{} trick if LuaTeX is used), but I wonder
>
>    - if there are drawbacks, and which, when loading xunicode on top of
>    tuenc
>    - if it has drawbacks to cheat xunicode and load it with LuaTeX
>    - if xunicode is now considered 'obsolete'
>    - whether it would make sense to strip all tipa-related code from
>    xunicode and set up a new package for fontspec-tipa support.
>
>
> Ross has promised an update to xunicode to work in luatex without having
to fake past the xetex test, however I think going forward it would be good
anyway to develop a new tipa specific package without loading xunicode or
EUx encodings which introduce a lot of dependencies and have definitions
that don't always match the ones in TU (due to bug fixes, such as for
\textquotesingle in the latex release that went to ctan last night)  or
just due to different choices in mapping to Unicode).

**Comment by wspr** [comment]
Like you say this isn't *really* a fontspec issue (although touches on fontspec, obviously). The intention with our rewrite of the encoding subsystem (TU) was that xunicode should still load — but as David says that comes with some baggage. In the short term I'd probably fall back on the `euenc` fontspec option — package authors should be polite enough to support that going forwards, and if not it's their fault not mine :)
