### ISSUE TITLE
\emph in footnote gives wrong result when footnote is in empt’ed text

### ISSUE THREAD

**Issue by tweh** [wspr/fontspec#283]
There is a problem when using `\emph` inside a footnote that itself is part of normal text enclosed in `\emph`: The highlights text in the footnote text isn’t set in italic since at this point the counter `\l__fontspec_em_int` is 1 instead of 0. A possible solution (or at least a workaround) to achieve the same result (as without loading `fontspec`) is to add a counter rest in `\normalfont`.

```latex
% !TeX program = xelatex
\documentclass{article}

\usepackage{fontspec}% (comment this out for normal/desired behaviour)

% possible solution reset em-counter with \normalfont
%\usepackage{etoolbox}
%\ExplSyntaxOn
%\appto\normalfont{
%   \int_gzero:N \l__fontspec_em_int
%}
%\ExplSyntaxOff

\begin{document}

Text\footnote{In \emph{normal} Text} Text

\emph{Text\footnote{In \emph{emph'ed} Text} Text}% the emph in the footnote is
                                                 % upright but should be italic

\emph{Emph'ed Text \emph{in} emph'ed Text}

\end{document}
```

**Comment by wspr** [comment]
Are you definitely using the latest version of the code?
This was a bug originally but the current release now contains:

```
% \begin{macro}{\reset@font}
% Ensure nesting resets when necessary:
%    \begin{macrocode}
\cs_set:Npn \reset@font
  {
    \normalfont
    \int_zero:N \l_@@_em_int
    \int_zero:N \l_@@_strong_int
  }
%    \end{macrocode}
% \end{macro}
```

Which I believe fixes this issue.

**Comment by ousia** [comment]
@tweh, I get expected results with latest `fontspec`.

**Comment by tweh** [comment]
Damn … I forgot to check the version `O:-)` it wasn’t the current one. Nevermind 

PS: Sorry for the late reply, I didn’t get a notification e-mail …

**Comment by wspr** [comment]
Thanks for the followup, no worry about the delay :) Glad to hear it's working now.
