### ISSUE TITLE
LuaLaTeX Ligatures-ResetAll swap_plus_minus_aux

### ISSUE THREAD

**Issue by RobtAll** [wspr/fontspec#284]
Ligatures=ResetAll produces an error:

    Argument of \__fontspec_swap_plus_minus_aux:Nq has an extra }

But Ligatures=CommonOff seems to be OK.

MWE:

    \documentclass{article}
    \usepackage{fontspec}
    \newfontfamily\foobar[Ligatures=ResetAll]{Latin Modern Roman}
    \begin{document}
    foo
    \end{document}

**Comment by wspr** [comment]
This should now have been fixed in the latest CTAN release.
