### ISSUE TITLE
BoldItalic instead of Italic with impallari fonts

### ISSUE THREAD

**Issue by icebearsoft** [wspr/fontspec#285]
When I use \textit{something} or even explicitely {\itshape \mdseries something}, I get bold italic instead of italic for Libre Caslon Text, Libre Bodoni, and Libre Baskerville. Other fonts from opentype /impallary, namely Cabin, Lobster Two, Quattrocento, and Raleway work as expected.
[bug.zip](https://github.com/wspr/fontspec/files/892572/bug.zip)

**Comment by eg9** [comment]
Here is a test file

    \documentclass[12pt]{article}
    
    \usepackage{fontspec}
    
    \newfontfamily{\caslon}{Libre Caslon Text}
    \newfontfamily{\basker}{Libre Baskerville}
    \newfontfamily{\bodoni}{Libre Bodoni}
    \newfontfamily{\cabin}{Cabin}% OK
    \newfontfamily{\lobster}{Lobster Two}% OK
    \newfontfamily{\quattro}{Quattrocento}% OK
    \newfontfamily{\raleway}{Raleway}% OK
    
    \newcommand{\test}[1]{%
      {#1Normal \textit{in textit} and {\itshape \mdseries in itshape mdseries}.}\par
    }
    
    \begin{document}
    
    \test{\caslon}
    \test{\basker}
    \test{\bodoni}
    \test{\cabin}
    \test{\lobster}
    \test{\quattro}
    \test{\raleway}
    
    \end{document}

<img width="290" alt="screen shot 2017-04-04 at 23 53 24" src="https://cloud.githubusercontent.com/assets/302839/24680626/f0a0c470-1991-11e7-9dd6-a6e6499cbd92.png">

The only failure seems to be with Libre Baskerville. A specific test

    \documentclass[12pt]{article}

    \usepackage{fontspec}
    \setmainfont{Libre Baskerville}

    \begin{document}

    Normal \textit{italic} \textbf{boldface} \textbf{\textit{boldface italic}}

    \end{document}

<img width="584" alt="screen shot 2017-04-04 at 23 58 17" src="https://cloud.githubusercontent.com/assets/302839/24680817/b0c080c4-1992-11e7-9319-bb74bf8305c9.png">

However, if I choose the font by file, the result is as expected

    \documentclass[12pt]{article}

    \usepackage{fontspec}
    \setmainfont{LibreBaskerville}[
      Extension=.otf,
      UprightFont={*-Regular},
      ItalicFont={*-Italic},
      BoldFont={*-Bold},
      BoldItalicFont={*-BoldItalic},
    ]

    \begin{document}

    Normal \textit{italic} \textbf{boldface} \textbf{\textit{boldface italic}}

    \end{document}

<img width="572" alt="screen shot 2017-04-05 at 00 05 49" src="https://cloud.githubusercontent.com/assets/302839/24681036/a8c630de-1993-11e7-8491-593d4b01cb9d.png">

**Comment by wspr** [comment]
This is almost certainly an engine problem, not fontspec. "Guessing" the italic/bold shapes is a heuristic and does fail for certain fonts from time to time. As @eg9 says, using the font name is the most reliable approach here.
