### ISSUE TITLE
Kerning options gives error with AAT font

### ISSUE THREAD

**Issue by tweh** [wspr/fontspec#287]
Hi,

now I’m using the current version (v2.6a) and run in the problem that the option `Kerning` now throws an error for an AAT rendered font, which wasn't the case in the previous version (don’t know the exact version number). The following example using [_Proza Libre_](https://github.com/jasperdewaard/Proza-Libre) only works with an explizit selection of the rendering mechanism.

```tex
% !TeX program = xelatex
\documentclass{article}

\usepackage{fontspec}
\setsansfont[
%   Renderer = OpenType
]{Proza Libre}

\begin{document}
\sffamily
TEST

\addfontfeatures{Kerning=Uppercase}
TEST
\end{document}
```

**file list**

```plain
 *File List*
 article.cls    2014/09/29 v1.4h Standard LaTeX document class
  size10.clo    2014/09/29 v1.4h Standard LaTeX file (size option)
fontspec.sty    2017/03/31 v2.6a Font selection for XeLaTeX and LuaLaTeX
   expl3.sty    2017/03/18 v7019 L3 programming layer (loader) 
expl3-code.tex    2017/03/18 v7019 L3 programming layer 
l3xdvipdfmx.def    
  xparse.sty    2017/03/18 v7019 L3 Experimental document command parser
fontspec-xetex.sty    2017/03/31 v2.6a Font selection for XeLaTeX and LuaLaTeX
 fontenc.sty
   tuenc.def    2017/02/22 v2.0g Standard LaTeX file
fontspec.cfg
 ***********
```

**Comment by wspr** [comment]
Sorry for the slow reply — can't promise a quick fix but I'll look into this as a first priority for the next round of fontspec updates.

**Comment by tweh** [comment]
Thanks. I’m not in a hurry, I finished the project with a previous version and a the moment don’t use an AAT font …

**Comment by wspr** [comment]
I finally dived back through the code to look into this, and it turns out there were never any AAT `Kerning` features — although it might not have given an error, as far as I know it couldn't have been doing anything :)

**Comment by tweh** [comment]
Thanks! So, can I assume, that manually selecting the `Renderer` is the proper way to go in this case?

**Comment by wspr** [comment]
Yes, if you want to use the Uppercase kerning option.

I didn’t realise that XeTeX defaulted to using the AAT renderer; if so that might be something that fontspec needs to provide an interface for.

Moreover, it doesn’t look like Proza Libre has AAT features available — is that actually the font you had the trouble with?

**Comment by tweh** [comment]
Yes it is. However, actually I have only a slight guess about the AAT features and don’t need them. But Proze was the font where I discovered the “bug” …
