### ISSUE TITLE
Errors while defining extra NFSS variants for a family

### ISSUE THREAD

**Issue by jmfarrow** [wspr/fontspec#292]
The following
```
\setmainfont{CMU Serif}[
  Ligatures=TeX,
  BoldFont={CMU Serif Extra},
  FontFace={bc}{n}{Font = CMUSerif-BoldNonextended, FakeStretch=0.8}
]
```
throws an unknown-key for Letters.

Using `FontFace={bc}{n}{CMUSerif-BoldNonextended}` but then obviously no stretching takes place.

A reminder from stackexchange:

> Looks like a bug to me. Probably the default setting of Letters=Smallcaps shouldn't be used when processing this font. Report it at github.com/wspr/fontspec/issues – Ulrike Fischer May 17 at 8:17

and, indeed commenting out the attempt to make small caps:

```
          \clist_put_left:Nn \l__fontspec_fontfeat_curr_clist {Letters=SmallCaps}
```

stops the error.

I'd make a patch so it only tries this under the right circumstances but my familiarity with both fontspec and the LaTeX3 interfaces aren't up to the task.

**Comment by u-fischer** [comment]
A complete example is at the tex.SX question:

https://tex.stackexchange.com/questions/370138/errors-while-defining-extra-nfss-variants-for-a-family-using-fontspec

**Comment by jmfarrow** [comment]
Looking into this further: this line
```
\__fontspec_keys_set_known:nxN {fontspec} {\l__fontspec_keys_leftover_clist} \l__fontspec_keys_leftover_clist
```
in `\__fontspec_get_features:Nn` is throwing the key error _which it shouldn't:_ it should just put the leftover unknown keys in `\l__fontspec_keys_leftover_clist`.

Looking deeper there appears to be a bug in `\keys_set_known:nn` which does the following:
```
\cs_new_protected:Npn \keys_set_known:nn #1#2
  {
    \bool_set_true:N \l__keys_only_known_bool
    \keys_set:nn {#1} {#2}
    \bool_set_false:N \l__keys_only_known_bool
  }
```
_i.e._ if there are nested calls to `\keys_set_known` going on (which I imagine could happen if the `.code` of a key is injecting or parsing further keys?), the state of `\l__keys_only_known_bool` will get lost and things will blow up at the end of the second-deepest `\keys_set_known` which is now in the wrong state.

**Comment by wspr** [comment]
@jmfarrow — thanks for the detailed investigations. While the expl3 code can be improved here, there's probably also an argument that fontspec could/should do things differently. I'll try to take a look some time…

**Comment by wspr** [comment]
Apologies for throwing this back at you, but I have to run now and if I don't reply right at this moment I'll probably forget for a few more weeks — is this issue now resolved with a recent expl3 update?

**Comment by jmfarrow** [comment]
Sorry, I've been occupied with another project and only just saw your comment.

Yes, I believe it was. At least I have a \WorkAroundKeysSetKnownBug_bool flag and it's currently set to false in my document and this particular issue seems to be working correctly with l3kernel 2017/09/18.
