### ISSUE TITLE
\fontspec_if_feature:nTF returns different values on XeLaTeX and LuaLaTeX

### ISSUE THREAD

**Issue by eg9** [wspr/fontspec#293]
The following code, compiled with XeLaTeX and LuaLaTeX follows different branches

fontspec 2017/03/31 v2.6a

It works as expected with TeX Live 2015 (but not 2016)

Reference: https://tex.stackexchange.com/questions/373920/

    \documentclass{article}
    
    \usepackage{ifxetex}
    \usepackage{fontspec}
    
    \setmainfont{Linux Libertine O}
    
    \newcommand{\engine}{\ifxetex Xe\else Lua\fi\LaTeX}
    
    \begin{document}
    
    \engine
    
    \ExplSyntaxOn
    \fontspec_if_feature:nTF {+sups} {TRUE} {FALSE}
    \ExplSyntaxOff
    
    \end{document}

**Comment by wspr** [comment]
Ah, I probably shortened a code path and removed stripping of the leading +. I guess that also affects the realscripts package. Thanks — will try to address shortly.

**Comment by eg9** [comment]
Indeed, the issue was raised in relation to `realscripts`.
