### ISSUE TITLE
Tie-after accent back to cmmi10

### ISSUE THREAD

**Issue by bgvoisin** [wspr/fontspec#294]
By default, for 8-bit TeX, the tie-after accent \t is taken from char "7F of the math italic font (plain TeX and OT1 LaTeX), usually cmmi10, or char "1A of the text companion font (T1/TS1 LaTeX), usually tcrm1000. With Unicode fonts and fonspec, when EU was the default encoding, xunicode.sty was read which included some clever code to use the "combining double inverted breve" at "0361 and allow both the plain TeX syntax "\t oo" and the LaTeX syntax "\t{oo}". Now, with TU the default encoding, xunicode.sty isn't read and tuenc.def includes nothing about \t, so we're back to using glyph "7F of cmmi10.

The problem is made more complex by the existence of two Unicode slots for the tie-after accents ("0361 for the combining accent and "2040 for the "character tie"), and the way existing fonts include them: to name but a few, STIX includes both accents, in both text and math fonts, Libertinus and Cambria include only the combining accent, in both text and math fonts, Latin Modern and TeX Gyre include only the character tie, in the text font only, and Lucida includes only the character tie, in the math font only.

A plain-style definition accounting for all three possibilities would be like (\fam0 the math family)

\def\t#1{%
  \iffontchar\font"0361 #1^^^^0361\else
  \iffontchar\font"2040 \accent"2040 #1\else
  {\edef\next{\the\font}\the\textfont0\accent"2040\next#1}\fi\fi}

Because of the combining accent, it would only work with input as "\t oo".

Sadly, it doesn't work well because the \accent primitive seems not to work in XeTeX and LuaTeX: the accent is placed too much to the left.

An alternative manual construction of the accent using \ialign, similar to the way \b, \c and \d are constructed in plain TeX, would be like

\def\talign#1{\leavevmode\vbox{%
  \baselineskip0pt \lineskip-1ex \lineskiplimit0pt%
  \ialign{##\crcr#1\crcr}}}
\def\t#1{\setbox0\hbox{%
  \iffontchar\font"0361\char"0361\else
  \iffontchar\font"2040\else\the\textfont0\fi\char"2040\fi}%
  \talign{\hidewidth\unhbox0\hidewidth\crcr#1}}

This would require input as "\t{oo}".

Sadly, there are problems with this approach too, as any left bearing before the accent (as for the original one in cmmi10) breaks the alignment.

A plain TeX file illustrating these various aspects is attached. (I tried to convert the code to LaTeX with fontspec and unicode-math, but gave up after a couple of hours of unsuccessful attempts. Sorry!)

I don't know what can or should be done about this matter. This is mostly a heads-up to point out that currently, with EU encoding, the tie accent glyph in the OpenType font, if any, isn't used at all.

A final aside: the xecjk package implements, in xunicode-addon.sty and xunicode-extra.def, an approach of \t apparently similar to that in the original xunicode.sty, but in LaTeX 3 syntax.

[tie-unicode.zip](https://github.com/wspr/fontspec/files/1078728/tie-unicode.zip)

**Comment by wspr** [comment]
Thanks Bruno! I guess this is an oversight in how we've put TU together. @davidcarlisle care to comment? How would this work with "plain" Unicode text? (Or doesn't it?)

**Comment by davidcarlisle** [comment]
>  when EU was the default encoding, xunicode.sty was read which included some clever code to use the "combining double inverted breve" at "0361 and allow both the plain TeX syntax "\t oo" and the LaTeX syntax "\t{oo}". 

xunicode just does

`\DeclareEncodedCompositeCharacter{\UTFencname}{\t}{0361}{0361}  % Combining double inverted breve`

looking at

\documentclass{article}
\showoutput
\usepackage[euenc]{fontspec}

\begin{document}

a\t ooa

a\t{oo}a

\end{document}


you get no accents just two

`Missing character: There is no ͡ in font [lmroman10-regular]:mapping=tex-text!`

with

```
\documentclass{article}
\usepackage{xunicode}
\showoutput
\begin{document}

a\t ooa

a\t{oo}a

\end{document}
```
You see xunicode doesn't really handle `\t{oo}` as you get two accents but encoded differently





> Now, with TU the default encoding, xunicode.sty isn't read and tuenc.def includes nothing about \t, so we're back to using glyph "7F of cmmi10.

That's an oversight, we should fix that in base/TU rather than fontspec.


This seems to do something sensible with U+0361 if it is available and U+2040 if it is available and currently gives up if neither, and works for \t oo and \t{oo}

actually this doesn't use the height of o or oo at all in the U+2040 case, it probably should, but that can be fixed

uses
 Arial as included (for 0361 comment that out to see latin modern (with 2040)

```

\documentclass{article}
\usepackage{fontspec}
\setmainfont{Arial}
\showoutput
\makeatletter

\def\talign#1{\leavevmode#1\vbox{%
\baselineskip0pt \lineskip-1ex \lineskiplimit\z@
\ialign{##\crcr\hidewidth\char"2040\hidewidth\cr\relax\crcr}}}


\DeclareTextCommand{\t}\UnicodeEncodingName[1]{%
 \iffontchar\font"0361
  \add@unicode@accent{"0361}#1\@empty
 \else
 \iffontchar\font"2040
  \talign#1\@empty
\else
?% something with the one in the OML math font, perhaps, like default \t
\fi\fi
}
\makeatother
\begin{document}

a


a\t ooa

a\t{oo}a


\end{document}
```

**Comment by bgvoisin** [comment]
> xunicode just does
> 
> \DeclareEncodedCompositeCharacter{\UTFencname}{\t}{0361}{0361} % Combining double inverted breve

Are you sure? I was referring also to the code 6 lines later (line 672 ff)

```
% LaTeX uses \t as  \t{oo}, so this needs implementing also:
\expandafter\expandafter\expandafter\let
 \expandafter\csname\expandafter \UTFencname\expandafter\string\expandafter\tie
  \expandafter\expandafter\expandafter\endcsname
  \expandafter\csname \UTFencname\string\t\endcsname
```

> with
> 
> \documentclass{article}
> \usepackage{xunicode}
> \showoutput
> \begin{document}
> 
> a\t ooa
> 
> a\t{oo}a
> 
> \end{document}
> 
> You see xunicode doesn't really handle \t{oo} as you get two accents but encoded differently
> 

Here your example works fine and the two "a\t ooa" and "a\t{oo}a" give the same output in pdf and in the console, with

```
...\hbox(6.9489+0.10999)x345.0, glue set 309.72fil
....\hbox(0.0+0.0)x15.0
....\TU/lmr/m/n/10 a
....\kern 0.03473 (for accent)
....\hbox(6.94444+0.0)x2.77779, shifted -0.00446
.....\OML/lmm/m/it/10 ^^?
....\kern -2.81252 (for accent)
....\TU/lmr/m/n/10 ooa
....\penalty 10000
....\glue(\parfillskip) 0.0 plus 1.0fil
....\glue(\rightskip) 0.0
...\glue(\parskip) 0.0 plus 1.0
...\glue(\baselineskip) 4.94112
```
appearing twice (where I think \OML/lmm/m/it/10 ^^? is the accent).

> uses
> Arial as included (for 0361 comment that out to see latin modern (with 2040)
> 
> \documentclass{article}
> \usepackage{fontspec}
> \setmainfont{Arial}
> \showoutput
> \makeatletter
> 
> \def\talign#1{\leavevmode#1\vbox{%
> \baselineskip0pt \lineskip-1ex \lineskiplimit\z@
> \ialign{##\crcr\hidewidth\char"2040\hidewidth\cr\relax\crcr}}}
> 
> \DeclareTextCommand{\t}\UnicodeEncodingName[1]{%
>  \iffontchar\font"0361
>   \add@unicode@accent{"0361}#1\@empty
>  \else
>  \iffontchar\font"2040
>   \talign#1\@empty
> \else
> ?% something with the one in the OML math font, perhaps, like default \t
> \fi\fi
> }
> \makeatother
> \begin{document}
> 
> a
> 
> a\t ooa
> 
> a\t{oo}a
> 
> \end{document}

That's wonderful! I've no idea how this works (#1 before the \vbox, not inside the \ialign), but it does indeed.

Regarding the third possibility (neither 0361 nor 2040 in the text font), \UseTextAccent{OML}{\t}{#1} seems to do the job. (But according to source2e.pdf it's fragile.)

Though the accent isn't taken, for Lucida OpenType, from 2040 in Lucida Bright Math OT if loaded via unicode-math. I've no idea how to refer to the math font in this case, testing seems to say that with unicode-math it's \textfont0. (Same as for luatex-math.tex, which is how this all started.)

Thats said, the presence of the accent in the math font instead of the text font seems a bug, dating back to when Lucida was ported over from Type 1 to OpenType. Karl Berry on the lucida-dev list is open to move the glyph to the text font.

Attached are files for the two examples above.

[davidsexamples.zip](https://github.com/wspr/fontspec/files/1082515/davidsexamples.zip)

**Comment by wspr** [comment]
@bgvoisin — thanks for the input here, I'm not 100% sure if further action is needed but if so best to continue in the LaTeX2e issue tracker where the TU encoding is now maintained.
