### ISSUE TITLE
Option to avoid the loading of a font.fontspec-file

### ISSUE THREAD

**Issue by u-fischer** [wspr/fontspec#296]
`fontspec` automatically loads a `font.fontspec` files if it can find it. This can be a problem if a font package in the texsystem contains a `.fontspec` file with settings that are wrong or unwanted in the current document. 

An example of a .fontspec-file giving a wrong font setup is described in my comment here:
https://tex.stackexchange.com/questions/373886/lualatex-and-texlive2017#comment924639_373886

Please add an option, e.g `UseFontspec=false", to suppress the loading of such file(s).

**Comment by wspr** [comment]
I always meant to include this as an option, thanks for the reminder.

What do you think of `NoFontCfg` as the name of the feature to activate this? Since the rest of fontspec doesn’t use the =true/false syntax, I’m trying to keep it consistent.

**Comment by u-fischer** [comment]
Hm. The file is not a cfg, also it sound as bit as if one doesn't want a configuration at all. What about NoFontspecFile or IgnoreFontspecFile?

**Comment by wspr** [comment]
On 27 Jun 2017, at 6:10 pm, u-fischer <notifications@github.com> wrote:
> 
> Hm. The file is not a cfg, also it sound as bit as if one doesn't want a configuration at all. What about NoFontspecFile or IgnoreFontspecFile?

Doesn’t have extension cfg but the documentation calls it a “font configuration file” I think :)
But you’re right that does sound like you want to ignore more than just the file.

I like your last suggestion `IgnoreFontspecFile` — it’s a bit verbose but I think it gets the idea across most clearly.

Thanks Ulrike!
