### ISSUE TITLE
`ccmp` support

### ISSUE THREAD

**Issue by stone-zeng** [wspr/fontspec#298]
How to use the OpenType feature `ccmp`? I know this feature is not supported by `fontspec` at present.

Some discussions can be found in [ccmp in Lua(La)TeX/ConTeXt, with Source Han serif font](https://tex.stackexchange.com/q/367113/136923).

**Comment by wspr** [comment]
I’m fairly sure that ccmp is enabled by default — it’s not the type of feature that users tend to need to activate/deactivate. But that reminds me these types of features (automatically on) should be discussed/documented somewhere.

The test file attached below works for me with the font linked at this page: https://blogs.adobe.com/CCJKType/2014/03/ids-opentype.html

It seems like the release version of Source Han Sans doesn’t support this particular feature yet.


\documentclass{article}
\ifdefined\XeTeXversion\else\usepackage{luaotfload}\fi
\begin{document}
\font\1="[Biang-Heavy.otf]" at 20pt\1
⿺辶⿳穴⿰月⿰⿲⿱幺長⿱言馬⿱幺長刂心
\end{document}

**Comment by Stone-Zeng** [comment]
Source Han Serif supports this feature. With XeTeX, I have got this glyph; however, with LuaLaTeX, it's not available.

XeTeX:
![xe](https://user-images.githubusercontent.com/18233088/27993261-2b70a9ac-64d9-11e7-8895-69415de6d01f.JPG)

LuaLaTeX:
![lua](https://user-images.githubusercontent.com/18233088/27993264-437c80e8-64d9-11e7-9704-00d7dca59ac7.JPG)

(I use Source Han Serif SC actually)

**Comment by wspr** [comment]
Thanks for the extra detail, I can confirm that Source Han Serif SC does show the behaviour you describe (working in XeTeX, not in LuaTeX). Which is really strange because "Biang-Heavy.otf” works in both engines.

This would now be a luaotfload / LuaTeX issue, or perhaps a font issue — fontspec can’t help any more here, I’m afraid.

**Comment by kumi123125** [comment]
⿺辶⿳穴⿰月⿰⿲⿱幺長⿱言馬⿱幺長刂心

**Comment by stone-zeng** [comment]
Now the following code can give the correct result:

```tex
% lualatex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{SourceHanSerifSC-Regular.otf}[Renderer=HarfBuzz]
\begin{document}
⿺辶⿳穴⿰月⿰⿲⿱幺長⿱言馬⿱幺長刂心
\end{document}
```

BTW Source Han Sans 2.002 has removed the `ccmp` feature since the character has been added in Unicode 13.
