### ISSUE TITLE
Warnings after updating fontspec to version 2.6d (2017/08/14)

### ISSUE THREAD

**Issue by miklmn** [wspr/fontspec#306]
Several fontspec warnings: "only-xetex-feature" are issued recently on code which worked previously.
The MWE taken from [here](https://tex.stackexchange.com/questions/387629/fontspec-only-xetex-feature-warning-hyphenchar):

```
\documentclass{minimal}
\usepackage{fontspec}
\setmonofont{Tex Gyre Cursor}
\begin{document}
Hello World
\end{document}
```

Resulting warning:

```
*************************************************          
* fontspec warning: "only-xetex-feature"                   
*                                                          
* Ignored XeTeX only feature: 'HyphenChar'.                
*************************************************
```

**Comment by Stone-Zeng** [comment]
I use XeTeX to compile, but still can see this annoying warning.

PS: the font name should be `TeX Gyre Cursor` with capital X.
