### ISSUE TITLE
\big, \bigg et al macros 

### ISSUE THREAD

**Issue by hvoss49** [wspr/fontspec#308]
There is some funny behaviour with all \big, \bigg and so on macros. For example:

```
\documentclass{article}
%\usepackage{fontspec}
\begin{document}
$\begin{array}{*{17}c}
() & [\,] & <> & /|\backslash & \lmoustache\,\rmoustache & \arrowvert\vert & \Vert\,\Arrowvert & 
\uparrow\downarrow & \updownarrow & \Uparrow\Downarrow & \Updownarrow & \langle\rangle & 
\lbrace\rbrace & \lceil\,\rceil & \lfloor\,\rfloor & \lgroup\rgroup & \bracevert  \\
%
\Bigg(\Bigg) & \Bigg[\,\Bigg] & \Bigg<\Bigg> & \Bigg/\Bigg|\Bigg\backslash & 
\Bigg\lmoustache\,\Bigg\rmoustache & \Bigg\arrowvert\Bigg\vert & \Bigg\Vert\,\Bigg\Arrowvert & 
\Bigg\uparrow\Bigg\downarrow & \Bigg\updownarrow & \Bigg\Uparrow\Bigg\Downarrow & 
\Bigg\Updownarrow & \Bigg\langle\Bigg\rangle & \Bigg\lbrace\Bigg\rbrace & 
\Bigg\lceil\,\Bigg\rceil & \Bigg\lfloor\,\Bigg\rfloor & \Bigg\lgroup\Bigg\rgroup & 
\Bigg\bracevert
\end{array}$
\end{document}
```

The output with [Computer Modern Math](http://hvoss.org/cmm.png) looks ok. Using Latin Modern Math (uncommenting package fontspec) gives different wrong results for [XeLaTeX](http://hvoss.org/xelatex2.png) and for [LuaLaTeX](http://hvoss.org/lualatex2.png).  I am using up-to-date TL2017 and Linux (Ubuntu)

**Comment by eg9** [comment]
I tried, but cannot reproduce the issue. I have updated my TeX Live (MacTeX) to the last possible minute. I just added `[4ex]` to your `array` in order to space the rows and `geometry` not to have an overfull box.

    \documentclass{article}
    \usepackage[a4paper,margin=2cm]{geometry}
    \usepackage{ifxetex,ifluatex}
    
    \ifxetex
      \usepackage{fontspec}
    \else
      \ifluatex
        \usepackage{fontspec}
      \fi
    \fi
    
    \begin{document}
    \ifxetex
      XeTeX
    \else
      \ifluatex
        LuaTeX
      \else
        pdftex
      \fi
    \fi
    
    \bigskip
    
    $\begin{array}{*{17}c}
    () & [\,] & <> & /|\backslash & \lmoustache\,\rmoustache & \arrowvert\vert & \Vert\,\Arrowvert & 
    \uparrow\downarrow & \updownarrow & \Uparrow\Downarrow & \Updownarrow & \langle\rangle & 
    \lbrace\rbrace & \lceil\,\rceil & \lfloor\,\rfloor & \lgroup\rgroup & \bracevert  \\[4ex]
    %
    \Bigg(\Bigg) & \Bigg[\,\Bigg] & \Bigg<\Bigg> & \Bigg/\Bigg|\Bigg\backslash & 
    \Bigg\lmoustache\,\Bigg\rmoustache & \Bigg\arrowvert\Bigg\vert & \Bigg\Vert\,\Bigg\Arrowvert & 
    \Bigg\uparrow\Bigg\downarrow & \Bigg\updownarrow & \Bigg\Uparrow\Bigg\Downarrow & 
    \Bigg\Updownarrow & \Bigg\langle\Bigg\rangle & \Bigg\lbrace\Bigg\rbrace & 
    \Bigg\lceil\,\Bigg\rceil & \Bigg\lfloor\,\Bigg\rfloor & \Bigg\lgroup\Bigg\rgroup & 
    \Bigg\bracevert
    \end{array}$
    \end{document}

Compiling with `pdflatex`, `xelate` and `lualatex` gives the following results

![screen shot 2017-10-06 at 13 30 23](https://user-images.githubusercontent.com/302839/31276332-9d11e50a-aa9b-11e7-879c-9e2180d12d7c.png)
![screen shot 2017-10-06 at 13 30 44](https://user-images.githubusercontent.com/302839/31276334-9d375c68-aa9b-11e7-88c0-4132930a7fc8.png)
![screen shot 2017-10-06 at 13 31 03](https://user-images.githubusercontent.com/302839/31276333-9d3757f4-aa9b-11e7-838c-e7b92790d78b.png)

**Comment by hvoss49** [comment]
Confirmed, on MacOSX it works fine, but my examples were created under Linux

**Comment by u-fischer** [comment]
I don't understand the remarks about computer modern math and latin modern math: fontspec doesn't change the math setup (at least not the delimiters) and you are not loading unicode-math, so I would expect that your example use the standard cmm fonts (cmex10.pfb etc) and this what happens. (I would not expect the wrong glyphs and I don't get them on windows).

**Comment by hvoss49** [comment]
As I already wrote when running under Linux _with_ loading fontspec, latex uses lmm and not cmm.With cmm all is fine.

**Comment by u-fischer** [comment]
It doesn't for me. Can you show the log-file of a lualatex compilation of the example with fontspec?

**Comment by hvoss49** [comment]
[FOO.log](https://github.com/wspr/fontspec/files/1363142/FOO.log)

**Comment by u-fischer** [comment]
You are loading unicode-math, and with it I can reproduce the issue.

**Comment by u-fischer** [comment]
With unicode-math the issue is easy to explain: \lmoustache and \rmoustache are not in the font, \arrowvert and the other "curious" outputs are not defined by unicode-math and so you get whatever the old mathcodes points to. The issue should be moved to the unicode-math issue tracker.
