### ISSUE TITLE
Split PDFs into "doc" and "code"

### ISSUE THREAD

**Issue by wspr** [wspr/fontspec#310]
In the end I think I want:

* fontspec.pdf — user documentation and API
* fontspec-code.pdf — code

**Comment by Stone-Zeng** [comment]
By the way, I hope you can provide an index with hyperlinks (for code). Sometimes it's really hard to find a specific command in pdf.

**Comment by wspr** [comment]
I can try, good idea :) Do you mean in the documentation or the code or both?

**Comment by Stone-Zeng** [comment]
Just for code is ok.

**Comment by wspr** [comment]
All done! New release on its way to CTAN.
