### ISSUE TITLE
fontspec cannot be loaded after babel any longer

### ISSUE THREAD

**Issue by ralessi** [wspr/fontspec#312]
With the latest versions of both `babel` and `fontspec`, this mwe compiled with `lualatex`:
```
\documentclass{article}
\usepackage[english]{babel}

\usepackage{fontspec}

\begin{document}
Hello world.
\end{document}
```
gives me this error:
````
ERROR: LaTeX error: "kernel/command-already-defined"

--- TeX said ---
! 
! Control sequence \latinencoding already defined.
! 
! See the LaTeX3 documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.121 \tl_new:N \latinencoding
````
pointing to l. 121 of fontspec-luatex.sty

If `fontspec` is loaded before `babel`, the mwe compiles. Are we now supposed to mind the load order of the two packages?

**Comment by wspr** [comment]
Apologies, this is an oversight. Thanks for letting me know.
Until I fix the bug and make a new release, you can work around the issue as follows:

\usepackage[english]{babel}
\let\latinencoding\relax
\usepackage{fontspec}

(or revert to the previous version)

**Comment by ralessi** [comment]
Many thanks!  I already did \let\latinencoding\relax: everything is now back to normal.
