### ISSUE TITLE
Font selection by font name

### ISSUE THREAD

**Issue by wehro** [wspr/fontspec#315]
On page 10 of the manual it is mentioned that one may use the `otfinfo -a` command to find out the font name. But if an Opentype font has a “family” as well as a “preferred family” (e. g. the Latin Modern fonts, use `otfinfo -i` to see it), the command outputs the “family”, which leads to an error message when used with `\fontspec` and similar commands. Fontspec seems to refer to the “preferred family” in these cases, so the documentation is misleading.

**Comment by wspr** [comment]
Thanks for the input. This has always been a fuzzy area. If you’d like to propose an update to the wording of the documentation via a pull request, it will greatly improve the chances of a fix appearing any time soon :)
