### ISSUE TITLE
\newfontfamily doesn't behave like `\new…`

### ISSUE THREAD

**Issue by wspr** [wspr/fontspec#319]
I think I should provide all of the following:

* `\setfontfamily` — a rename of the current `\newfontfamily`
* `\newfontfamily` —  check for csname as usual
* `\renewfontfamily` — check that the current defn is from `\newfontfamily`

**Comment by eg9** [comment]
I second this; a package might use `\newfontfamily{\strangescriptfont}{Strange Font}`, but the end user might prefer (or be forced to) using a different font. So the package should do

```latex
\setfontfamily{\strangescriptfont}{Strange Font} % better than \newfontfamily
```
and the end user can do
```latex
\renewfontfamily{\strangescriptfont}{Better Font}
```

**Comment by wspr** [comment]
@eg9 — just to clarify, why is it better if the package uses the `set` version? Don't you think the `new` version makes sense to ensure it's not conflicting with a macro from another class or package?

**Comment by eg9** [comment]
@wspr I was thinking to “basic” packages such as `xeCJK`, that sets a default CJK font,  or `xepersian`. For them a `\setfontfamily` (or an internal command based on it) should be the choice. Otherwise, I don't see much use for the command.

**Comment by wspr** [comment]
Hmm, should I provide `\providefontfamily` ?

**Comment by eg9** [comment]
@wspr Having the whole set is likely better. Maybe in packages `\setfontfamily` should be `\DeclareFontFamily`, for uniformity; unfortunately, it's taken. `;-)`
