### ISSUE TITLE
Asterisk (*) in listings environment becomes lower

### ISSUE THREAD

**Issue by Stone-Zeng** [wspr/fontspec#324]
Consider the following code:

```tex
\documentclass{article}
\usepackage{listings,fontspec}

\newfontfamily\CodeFont{Source Code Pro}
\setmonofont{Source Code Pro}

\begin{document}

{CodeFont: \CodeFont emph*}

{ttfamily: \ttfamily emph*}

\begin{lstlisting}[basicstyle=\CodeFont]
\CodeFont:
\emph*{hello}
\end{lstlisting}

\begin{lstlisting}[basicstyle=\ttfamily]
\ttfamily:
\emph*{hello}
\end{lstlisting}

\end{document}
```

The result is

![image](https://user-images.githubusercontent.com/18233088/39671518-55c90748-514c-11e8-980f-95e972b65d7b.png)

Notice that the asterisk is lower when using `\CodeFont`, but it's normal for `\ttfamily`.

I have tried other fonts. This issue appears when using Fira Code, Libertinus Mono etc, but doesn't show for CMU Typewriter.

Another test for Lucida Sans Unicode, however, shows that the asterisk (`U+002A`) becomes math asterisk (`U+2217`) improperly:

![image](https://user-images.githubusercontent.com/18233088/39671599-cb1aa546-514d-11e8-8b12-5e88bd5d20a5.png)

**Comment by qinglee** [comment]
AFAIK this issue has nothing to do with fontspec. It is the black magic of the listings package.

We can see the following code fragment in `listings.sty`:

```latex
\lst@CCPutMacro
    ...
    \lst@ProcessOther {"2A}{\lst@ttfamily*\textasteriskcentered}
    ...
    \@empty\z@\@empty
\def\lst@ttfamily#1#2{\ifx\f@family\ttdefault#1\relax\else#2\fi}
```

The definition of `\textasteriskcentered` is located in the file `tuenc.def`:

```latex
\DeclareTextCommand{\textasteriskcentered}\UnicodeEncodingName{%
  \iffontchar\font"2217 \char"2217 \else
    \begingroup
      \fontsize
       {\the\dimexpr1.2\dimexpr\f@size pt\relax}%
       {\f@baselineskip}%
      \selectfont
      \raisebox{-0.6ex}[\dimexpr\height-0.6ex][0pt]{*}%
    \endgroup
  \fi
}
```

**Comment by Stone-Zeng** [comment]
Everything goes OK after loading the `xunicode` package. I guess that this problem appears because `fontspec` and `ctex` all become independent of `xunicode` recently.

**Comment by qinglee** [comment]
`\textasteriskcentered` is exactly the same as `*` (`U+002A`) in `xunicode`:

```latex
\DeclareUTFcharacter[\UTFencname]{x002A}{\textasteriskcentered}
```

**Comment by wspr** [comment]
Interesting discussion but I agree this isn't a fontspec issue.
