### ISSUE TITLE
High amount of CharacterVariant values crashes

### ISSUE THREAD

**Issue by svenper** [wspr/fontspec#333]
## Description
Using more than a certain number of `CharacterVariant`s and specifying more options, e.g. `Color` in this case, crashes with an error. Removing the `Color` option allows more `CharacterVariant`s (in my case, just add `,22` to the values).

* [ ] Relevant for XeTeX
* [x] Relevant for LuaTeX
* [x] Issue tracker has been searched for similar issues?

## Minimal example demonstrating the issue
```tex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{iosevka-type-slab-regular}[
  Color=AA0000,
  CharacterVariant={1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21},
]

\begin{document}
ailg0\textasciitilde*\_\P{}gm\^{}@ß\{\}\$tQ\#3y1f
\end{document}
```

## Further details
I could not find a font in TeX Live with this many character variants. The font I used in the MWE is available on [be5invis/Iosevka](/be5invis/Iosevka/releases) (I used `07-iosevka-type-slab-*.zip`).

**Comment by wspr** [comment]
Interesting! It works for XeLaTeX but not for LuaLaTeX. This *appears* to be a luaotfload or LuaTeX bug, as shown here:

```
\documentclass{article}
\ifdefined\XeTeXversion\else\usepackage{luaotfload}\fi
\begin{document}
\font\x="[iosevka-type-slab-regular.ttf]:mode=node;script=latn;language=DFLT;+tlig
;+cv01=0;+cv02=0;+cv03=0;+cv04=0;+cv05=0;+cv06=0;+cv07=0;+cv08=0;+cv09=0;+cv10=
0;+cv11=0;+cv12=0;+cv13=0;+cv14=0;+cv15=0;+cv16=0;+cv17=0;+cv18=0;+cv19=0;+cv20
=0;+cv21=0;color=AA0000FF;"\x

ailg0\textasciitilde*\_\P{}gm\^{}@ß\{\}\$tQ\#3y1f
\end{document}
```

Any ideas from others?

**Comment by svenper** [comment]
You are right about XeLaTeX, I must have made a mistake as it works as expected for me now.

**Comment by wspr** [comment]
No mistake, I can see the problem too. Even if it’s not affecting your current document I’d like to chase this down with the luaotfload team...

**Comment by wspr** [comment]
I've opened an issue in the luaotfload tracker: https://github.com/lualatex/luaotfload/issues/424

So I'll close this here for now.
