### ISSUE TITLE
\hbar not displayed with fontspec on XeLaTeX/LuaLaTeX

### ISSUE THREAD

**Issue by aminophen** [wspr/fontspec#337]
## Description

See https://tex.stackexchange.com/questions/448490

## Check/indicate
- [x] Relevant for XeTeX
- [x] Relevant for LuaTeX
- [x] Issue tracker has been searched for similar issues?
- [x] Links to <tex.stackexchange.com> discussion if appropriate

## Minimal example demonstrating the issue
```
\documentclass{article}
\usepackage{fontspec}
\begin{document}
[$\hbar$]
\end{document}
```

## Further details

Looking into fontspec-math.dtx, accents (\grave, \acute, \bar etc.) are all handled specially so that operators font is always used. Why no such kind of redefinition for \hbar?

**Comment by wspr** [comment]
Hmm, while I don't think fontspec is the right place to do all of these redefinitions, I guess you're right that it should at least try, here.

I've added something, but it probably only works with the default fonts.
