### ISSUE TITLE
Font File Path

### ISSUE THREAD

**Issue by craigbass76** [wspr/fontspec#340]
## Description
Just wondering how to declare **where** an otf file is. I'd like to be able to zip up anything (font files included) someone would need to recreate what I'm trying to do (convert markdown walkthroughs to pdf with a  shell script) with little hassle.

I have put it in a fonts directory, relative to where I am running my command, in a fonts directory within where the LaTeX template sits, and I've tried sticking it right in the same directory as the template. I'm running this:
`pandoc -s --template="xyz.latex" markdown.md --pdf-engine=xelatex -o pdfs/xyz.pdf`

This is the WHOLE template file:
```
%!TEX TS-program = xelatex
\documentclass[11pt,oneside,a4paper]{article}
\usepackage{hyperref}
\def\tightlist{}

\usepackage{fontspec}
    \setmainfont{"OmnesLight.otf"}
\begin{document}
$body$
\end{document}
```

And this all works fine if I have Omnes installed on my system, and stick ` \setmainfont{Omnes Light}` in there instead. Like I said though, I'd like this setup to be portable. It's going to be something dumb I'm missing, I already know it. :)

**Comment by Stone-Zeng** [comment]
`\setmainfont{OmnesLight.otf}[Path=./fonts/]`. assuming that your fonts is in the `fonts` directory.

**Comment by wspr** [comment]
Yep, agreed with Xiangdong Zeng. I also agree with the sentiment that using the filename is more portable and reliable.

Note if you might also like to look at the .fontspec file possibility to streamline the source.

**Comment by craigbass76** [comment]
Awesome. I knew it was something simple. I'm going to need to specify a 
monospace font too, so I like the idea of the fonts directory. Then I 
can keep whatever I'll need in there.

Thanks folks. This little project is starting to shape up...
