### ISSUE TITLE
Combining accents break Source Code Pro spacing

### ISSUE THREAD

**Issue by tspiteri** [wspr/fontspec#341]
For Source Code Pro, using combining accents breaks the letter spacing. I did not have this issue for Latin Modern Mono or FreeMono.

This is with LuaTeX, Version 1.07.0 (TeX Live 2018)

```latex
\documentclass[12pt]{article}
\usepackage{fontspec}
\begin{document}

\setmainfont{lmmono12-regular.otf}
Combining: aȧa cċc. Not combining: cċc.

\setmainfont{FreeMono.ttf}
Combining: aȧa cċc. Not combining: cċc.

\setmainfont{SourceCodePro-Regular.otf}
Combining: aȧa cċc. Not combining: cċc.

\end{document}
```

I'm attaching a screenshot for this example. The first two lines look fine. With Source Code Pro, the characters with combining accents (a followed by U+0307, then c followed by U+0307) have extra space to their right.

![combining](https://user-images.githubusercontent.com/18604588/49882653-58b66080-fe31-11e8-9732-283bcd32aef7.png)

**Comment by wspr** [comment]
This is almost certainly a bug in the font itself. I'm afraid these kinds of issues are entirely outside of fontspec's control — my package just loads the font. 

The only workaround from the fontspec perspective would be to use LaTeX markup for the accents and ensure the one that works is used. Part V in the manual ("Commands for accents and symbols") explains how this can be done.

**Comment by eg9** [comment]
It should be noted that the issue doesn't appear with XeLaTeX

<img width="589" alt="screen shot 2018-12-12 at 23 32 22" src="https://user-images.githubusercontent.com/302839/49903073-37bc3280-fe66-11e8-98d0-09f3729a1efe.png">
