### ISSUE TITLE
Xetex support for localized .otf features

### ISSUE THREAD

**Issue by samiel60** [wspr/fontspec#343]
Fontspec does not adequately support the localized features (calt and locl) of the .otf fonts.

Relevant for XeTeX

An .otf font that contains localized features such as Contextual Alternates (`calt`) for certain languages ​​or Localized Forms (`locl`), which refer physiologically to certain languages, does not implement the substitutions indicated for those languages, but follows the general indications (`DFTL {dflt }`) indicated in the respective lookups of the font itself. For example, this happens with the local substitution (for French and Italian languages) of GaramondPremierePro and `quoteright` and `quoteright.fr` glyphs.

To avoid repeating questions already discussed, refer to this first thread:
[https://github.com/wspr/fontspec/issues/322](url)
which provides a solution to the problem,
and to this second thread:
[https://tex.stackexchange.com/questions/467943/xetex-support-for-otf-features](url)
which highlights how the solution there provided actually produces other serious problems.

**Comment by wspr** [comment]
Please provide a minimal example and public link to a font for testing.

`calt` is provided by the `Contextuals = Alternate` option. `locl` is automatically applied (IIRC) but this should be documented better. (I need to confirm with XeTeX & luaotfload.)

**Comment by samiel60** [comment]
Consider the uploaded font:
[https://www.dropbox.com/s/wm2g8ho5rp5itsj/samiel.otf?dl=0](url)
It contains a Contextual Alternate lookup (Lookup no.15) connected to a Single Substitution lookup (Lookup no. 17): for Franch and Italian languages, after any letter the `quoteright` glyph must be replaced by `quoteright.fr`. For illustrative reason, I applied a paroxysmal bearing to the second glyph.
You can see it into the font, or in the following .fea file:
[https://www.dropbox.com/s/s1j2bwn8xlnktjn/samiel.fea?dl=0](url)
With LibreOffice I write the same string, apply Italian for the first one and English for the second one. It's evident that in the first case the apostrophe bearing is very wide.
With XeTeX and the following code:
```
\documentclass{article}
\usepackage{fontspec}
\setmainfont[Ligatures=TeX,Numbers=OldStyle,Contextuals=Alternate]{samiel}
\usepackage{polyglossia}
\setmainlanguage[babelshorthands=true]{italian}
\setotherlanguages{english}

\begin{document}

\emph{Xetex}

N’I H’E I’P (Italian)

\begin{english}N’I H’E I’P (English)\end{english}

\end{document}
```
nothing happens. I receive the warning:
```
Package fontspec Warning: OpenType feature 'Contextuals=Alternate' (calt) not
(fontspec)                available for font 'samiel' with script
(fontspec)                'Latin' and language 'Default'.
```
You can see the result in the following pic:
[https://www.dropbox.com/s/5gpqlgwikm1nepx/samiel.png?dl=0](url)
Is there anything wrong or missing in my XeTeX code? Or is it a defective support of XeLateX for this feature?
The same for `locl` feature. For instance, the same glyphs substitution (apostrophe) in Adobe GaramondPremierPro is made by a `locl`, but with a code like the one I furnished, the probleme is the same. No differences changing language...

**Comment by u-fischer** [comment]
As I already tried to explain in https://tex.stackexchange.com/a/467953/2388 your code is wrong. polyglossia doesn't apply the open type language setting to the font when switching languages. If you want language dependant open type features you **must** use babel .

**Comment by samiel60** [comment]
Yes, but as I wrote there, the code you furnished me causes some others troubles.
The code I compiled doesn't use onum (proportional numbers) for lacks the relative settings, but use monospaced old style. You wrote: «Well the warning seems to be wrong, the numbers are oldstyle»: no, warning is correct for only (oldstyle) tnum and not (oldstyle) onum are used.
Moreover, it lacks a lot of feature as small caps al lining numbers.
Ok, you're right: it's mandatory to use babel, but evidently the code must be emproved to preserve **all** font features...

**Comment by u-fischer** [comment]
May be. But if you want to report a fontspec issue, you should show code that demonstrates a fontspec problem, not some arbitrary code that can't work anyway. Beside this, you should at first test with low level commands. If I run this

~~~~
\documentclass{article}

\begin{document}
\font\test="[SamielPro.otf]/OT:script=latn;language=DFLT;"
\test 12345

\font\test="[SamielPro.otf]/OT:script=latn;language=ITA;"
\test 12345

\font\test="[SamielPro.otf]/OT:script=latn;language=DFLT;+onum;"
\test 12345

\font\test="[SamielPro.otf]/OT:script=latn;language=ITA;+onum;"
\test 12345

\font\test="[SamielPro.otf]/OT:script=latn;language=DFLT;+lnum;"
\test 12345

\font\test="[SamielPro.otf]/OT:script=latn;language=ITA;+lnum;"
\test 12345

\font\test="[SamielPro.otf]/OT:script=latn;language=DFLT;+pnum;"
\test 12345

\font\test="[SamielPro.otf]/OT:script=latn;language=ITA;+pnum;"
\test 12345

\font\test="[SamielPro.otf]/OT:script=latn;language=DFLT;+tnum;"
\test 12345

\font\test="[SamielPro.otf]/OT:script=latn;language=ITA;+tnum;"
\test 12345
\end{document}
~~~~

I get 

![image](https://user-images.githubusercontent.com/4047173/50559129-1aa3b280-0cf4-11e9-803c-5a571c0bd241.png)

Which looks as if your font doesn't really do everything right.

**Comment by samiel60** [comment]
oh thank you! I've to reconsider all :(

**Comment by samiel60** [comment]
Improved with some changes to Lookups Metadata!

**Comment by samiel60** [comment]
if the basic code is:
`\babelfont{rm}[Ligatures=TeX,Numbers=OldStyle]{samiel.otf}`
how can I have Italic (and bold) too?
For
`\babelfont{it}[Ligatures=TeX,Numbers=OldStyle]{samiel-Italic.otf}`
doesn't work...

**Comment by u-fischer** [comment]
An issue tracker is not the right place for such questions. Close the issue and ask your questions on tex.sx.
