### ISSUE TITLE
Setting Scale=1 on \rmfamily still scales mainfont

### ISSUE THREAD

**Issue by adunning** [wspr/fontspec#345]
## Description
In response to #165, a workaround was added to prevent scaling of the main font against the 'old default'. I'm finding that the solution there (and in the manual, ¶6.2 Scale) doesn't actually have any effect. In the case of loading Junicode, it's being scaled up to match Latin Modern.

## Check/indicate
- [X] Relevant for XeTeX
- [X] Relevant for LuaTeX
- [X] Issue tracker has been searched for similar issues?
- [x] Links to <tex.stackexchange.com> discussion if appropriate

## Minimal example demonstrating the issue
```latex
\documentclass{article}
\usepackage{fontspec}
\defaultfontfeatures{Scale=MatchLowercase}
\defaultfontfeatures[\rmfamily]{Scale=1}
\setmainfont{Junicode}

\begin{document}
	
	Test
	
\end{document}
```

## Further details

In the log:

```
Package fontspec Info: Junicode/BI scale = 1.031176985981308.

Package fontspec Info: Font family 'Junicode(0)' created for font 'Junicode'
(fontspec)             with options [Scale=MatchLowercase,Scale=1].
```

**Comment by RuixiZhang42** [comment]
There is no problem in the actually output and you may consider to close this issue. Here is how you can check if Junicode is *really* scaled:

    % !TeX program = XeLaTeX
    \documentclass{article}
    \usepackage{fontspec}
    \defaultfontfeatures{Scale=MatchLowercase}
    \defaultfontfeatures[\rmfamily]{Scale=1}
    \setmainfont{Junicode.ttf}
    
    \begin{document}
    Test \the\fontdimen6\font\relax
    \end{document}

This is the output:

![Junicode](https://user-images.githubusercontent.com/39968857/51054442-dbeee180-15aa-11e9-83f4-ffff5c9360fb.png)

Indeed, the more *complete* log file says:

    Package fontspec Info: Junicode scale = 1.031176985981308.
    % The above info is simply a report on \defaultfontfeatures{Scale=MatchLowercase}
    
    Package fontspec Info: Font family 'Junicode.ttf(0)' created for font
    (fontspec)             'Junicode.ttf' with options
    (fontspec)             [Scale=MatchLowercase,Scale=1]. % <- This is what is important
    (fontspec)              
    (fontspec)              This font family consists of the following NFSS
    (fontspec)             series/shapes:
    (fontspec)              
    (fontspec)             - 'normal' (m/n) with NFSS spec.:
    (fontspec)             <->s*[1]"[Junicode.ttf]/OT:script=latn;language=DFLT;" % <- scale = 1
    (fontspec)             - 'small caps'  (m/sc) with NFSS spec.:
    (fontspec)             <->s*[1]"[Junicode.ttf]/OT:script=latn;language=DFLT;+sm % <- scale = 1
    cp;"

**Comment by adunning** [comment]
Thanks for the explanation; it seems I was merely misinterpreting the log.
