### ISSUE TITLE
script and lang missing in font definition.

### ISSUE THREAD

**Issue by u-fischer** [wspr/fontspec#349]
## Description
fontspec (2019/01/18 v2.6l) writes "Font "OpenSans-Regular" does not contain any OpenType  `Script' information." and then doesn't add script and language tag.

## Check/indicate
- [ x] Relevant for XeTeX
- [ x] Relevant for LuaTeX
- [ x] Issue tracker has been searched for similar issues?

## Minimal example demonstrating the issue
```
\documentclass{article}
\usepackage{fontspec}
\setmainfont{OpenSans-Regular.ttf}
\begin{document}
blub
\end{document}
```

## Further details

I 'm not sure if the current behaviour is actually more correct, but it is certainly a change. For some fonts (I found opensans, times and arial) I get no script and language tag in the font features. 

The log-file says 

~~~
Package fontspec Info: Font "OpenSans-Regular" does not contain any OpenType
(fontspec)             `Script' information.


Package fontspec Info: Font family 'OpenSans-Regular.ttf(0)' created for font
(fontspec)             'OpenSans-Regular.ttf' with options [Ligatures=TeX].
(fontspec)              
(fontspec)              This font family consists of the following NFSS
(fontspec)             series/shapes:
(fontspec)              
(fontspec)             - 'normal' (m/n) with NFSS spec.:
(fontspec)             <->"[OpenSans-Regular.ttf]:mode=node;+tlig;"
~~~

Trying to force the script with e.g. `\setmainfont{times.ttf}[Script=Greek]` doesn't work. 

otfinfo says:

~~~
$ otfinfo -s OpenSans-Regular.ttf
latn            Latin
latn.MOL        Latin/Moldavian
latn.ROM        Latin/Romanian
~~~

For other fonts it still works. The main difference I saw is that working fonts have DFLT in their script list.

**Comment by u-fischer** [comment]
Additional remark: I do have in the luaotfload testsuite suddenly also quite a number of test failures related to unicode-math. A number of boxes have suddenly a different width. A possible cause could be that the math fonts are loaded without the script=math feature:

~~~~
[texgyrepagella-math.otf]:mode=base;
~~~~

**Comment by RuixiZhang42** [comment]
Which version of `fontspec` is used for the above discrepancies? AFAIK, all current script/language issues seem to be related to #346, which unfortunately is not fixed in the `v2.6k` CTAN release. #346 is, however, fixed in the working branch of `v2.6l`.

**Comment by wspr** [comment]
Thanks for the detailed analysis. You're right, it is a change, and it is indeed a bug :( I think I have this fixed now in the `working` code but want to make doubly sure everything is working properly with unicode-math before I release...

**Comment by u-fischer** [comment]
I did run my (luaotfload)-testsuite with the new version (so only with luatex ...). The unicode-math failures are gone, I have one failure because a font id number has changed, but that's imho harmless. I also get a failure because scaling has slightly changed:

~~~
\documentclass{article}
\usepackage{fontspec}
\setmainfont{texgyretermes-regular.otf} 
\begin{document}
\fontspec[Scale=MatchLowercase]{texgyrecursor-regular.otf} 

\typeout{font dimen 5: \the\fontdimen5\font}

\typeout{font dimen 8: \the\fontdimen8\font}

\end{document}
~~~~

This output with  2019/01/18 v2.6l
~~~~
font dimen 5: 4.49998pt
font dimen 8: 6.07552pt
~~~~

and with the experimental code
~~~~
font dimen 5: 4.50005pt
font dimen 8: 6.07559pt
~~~~

**Comment by RuixiZhang42** [comment]
@u-fischer https://github.com/wspr/fontspec/commit/0911d7557d6d0938180684dcb3ad9a742e64f775 contains the exact same changes in font size, e.g., in `feat-scale-match.luatex.tlg` and `feat-scale-match.xetex.tlg`. The change has to do with the `1sp`, `2sp` and `3sp` introduced in https://github.com/wspr/fontspec/commit/1c1f6319926819793f74489d0665406786b25f83, https://github.com/wspr/fontspec/commit/f0d6341c9f5746d50ea129f7e0ed896439fd8415 and https://github.com/wspr/fontspec/commit/0911d7557d6d0938180684dcb3ad9a742e64f775. I&nbsp;suspect this is the desired change.

**Comment by u-fischer** [comment]
@RuixiZhang42 Ah yes. My testfile is a copy from this one.

**Comment by wspr** [comment]
The ± 1sp, 2sp, 3sp thing was added as an additional measure to avoid XeTeX “caching” the fontname — strictly I could remove them but I hoped the differences were small enough that they wouldn’t affect too much in practice.

I could revert if you think even such small changes are problematic :)

**Comment by u-fischer** [comment]
I personally don't care much about the scaling difference. But I think an update would be good as the missing script is starting to show e.g. https://tex.stackexchange.com/questions/471565/realscripts-fontspec-update-vs-some-opentype-fonts and https://tex.stackexchange.com/questions/471184/problem-with-prime-and-unicode-math-package

**Comment by wspr** [comment]
Scaling is back to normal. New release sent to CTAN.
