### ISSUE TITLE
Scale* or Rescale

### ISSUE THREAD

**Issue by wspr** [wspr/fontspec#350]
## Description
For unicode-math we need a way for multiple Scale options to be multiplicative.
E.g.,

    Scale*=1.1,Scale*=1.1

should be equivalent to 

    Scale = 1.21

I could overload `Scale` but I'm a little worried about backwards compatibility.

**Comment by RuixiZhang42** [comment]
I am copying my comment in https://github.com/wspr/unicode-math/issues/287 here:

> If a new key were to be introduced, I would suggest `CompoundScale` as in “compound interest”, which [also] implies that the operation is multiplicative.

A new key is better for sure when it comes to backwards compatibility.

**Comment by RuixiZhang42** [comment]
Here is an idea: How about an “overwrite”-style `Scale` (as is now) and a “multiplicative”-style `CompoundScale`? So that

    Scale=1.1,Scale=1.2,CompoundScale=1.3,CompoundScale=1.4

produces an overall scaling of `1.2 × 1.3 × 1.4 = 2.184`, and `unicode-math` could issue `CompoundScale=1.00001` and `CompoundScale=0.99999` for families&nbsp;2 and&nbsp;3, respectively.

**Comment by wspr** [comment]
I like it a lot! I think as a general feature the name “CompoundScale” is good as it shouldn’t be that useful that often. If (for some reason) people find it very useful I can add the less description but terse name Scale* as a synonym at a later date.

**Comment by RuixiZhang42** [comment]
Need a check on whether `Scale` is empty or not:

    \fontspec[Scale=1,ScaleAgain=1.1]{texgyreheros-regular.otf}%% <- This works

    \fontspec[ScaleAgain=1.1]{texgyreheros-regular.otf}%%%%%%%%%% <- This produces error

**Comment by wspr** [comment]
Yes indeed, good catch!
