### ISSUE TITLE
fontspec documentation too dogmatic about filename lookup

### ISSUE THREAD

**Issue by kberry** [wspr/fontspec#353]
fontspec.pdf (page 11 in distributed pdf) says:

Fonts selected by filename must include bold and italic variants explicitly.

Ok, it's kind of true, but misleading, because the next page is what talks about .fontspec files, which we invented precisely to avoid the need to explicitly specify everything. As you know.

So I suggest/request changing the wording here, as in "..., unless a .fontspec file is supplied for the font family (see next page). We'll give some first examples specifying everything explicitly."

Something along those lines. Whatever. --thanks, k.

**Comment by wspr** [comment]
Yes, good thinking, thanks.
