### ISSUE TITLE
fontspec not working on fresh install

### ISSUE THREAD

**Issue by Im-Sum-Guy** [wspr/fontspec#355]
Hey, I'm using TexStudio and installed fontspec via the built in package manager and found that it wasn't working, regardless of whether I was compiling with XeLaTex or LuaLaTex. Even after a fresh install of MikTex, I still get the same issue:
LaTeX error: "kernel/invalid-variant" Variant form 'e' invalid for base form '\tl_if_empty_p:n'. For immediate help type H <return>. \cs_generate_variant:Nn \tl_if_empty_p:n {e}

This happens simply when trying to load the package. Here is the minimal example that generated this error:
\documentclass{article}
\usepackage{fontspec}
\begin{document}
	Hello world
\end{document}

I think that there is either some kind of version incompatibility somewhere, or a required package can't get accessed. I tried including "\usepackage{xparse}" for example, but to no effect. I've been banging my head against the wall for a while on this so I would greatly appreciate any insight into what may be going on!

**Comment by wspr** [comment]
Apologies, the “e” variant is a relatively new addition to the l3kernel code and intended to target 2019 installations.

Does it work if you upgrade your versions of l3kernel ?

Best regards,
Will

**Comment by eg9** [comment]
@Im-Sum-Guy  No error with a fully updated TeX Live
