### ISSUE TITLE
More packages inclusions for no-math

### ISSUE THREAD

**Issue by RuixiZhang42** [wspr/fontspec#357]
This is more of a feature request and should be fairly easy to be implemented.

I&nbsp;was wondering if 3 more math font packages can be included in `\fontspec_maybe_setup_maths:` from `fontspec-code-math.dtx`, namely, `newpxmath`, `newtxmath` and `mtpro2`. Maybe with 2 more: `pxfonts` and `txfonts`?

```tex
  \@ifpackageloaded{pxfonts}      {\bool_gset_false:N \g_@@_math_bool}{}
  \@ifpackageloaded{txfonts}      {\bool_gset_false:N \g_@@_math_bool}{}
  \@ifpackageloaded{newpxmath}    {\bool_gset_false:N \g_@@_math_bool}{}
  \@ifpackageloaded{newtxmath}    {\bool_gset_false:N \g_@@_math_bool}{}
  \@ifpackageloaded{mtpro2}       {\bool_gset_false:N \g_@@_math_bool}{}
```

**Comment by wspr** [comment]
Thanks!
