### ISSUE TITLE
Problem with luatex 1.10.1 and fontspec

### ISSUE THREAD

**Issue by hvoss49** [wspr/fontspec#364]
## Description
Problem with fontspec and new luatex 1.10.1

## Check/indicate
- [x] Relevant for LuaTeX
- [x] Issue tracker has been searched for similar issues?

## Minimal example demonstrating the issue

```
\documentclass{article}
\usepackage{fontspec}
\setmainfont{LibertinusSerif-Regular.otf}
\begin{document}
foo \textsc{Foomatik}
\end{document}
```

The above worls well with `luatex 1.10.0`, but _not_  with `luatex 1.10.1`. There are no Small Caps. Without `fontspec` and using `\input luaotfload.sty` and `luatex` it is fine.

**Comment by wspr** [comment]
Thanks Herbert. I wonder if this is a luaotfload issue; could you try the following minimal example?

```
\documentclass{article}
\begin{document}
\font\2="[texgyrepagella-regular.otf]:+smcp"
\2 foo

\directlua{
x = luaotfload.aux.provides_feature(font.id("2"), "LATN", "dflt", "smcp")
if x then
  tex.print("has small caps")
else
  tex.print("no small caps")
end
}
\end{document}
```

I don't have luatex 1.10.1 yet — for me this prints "foo\par has small caps" in Pagella small caps.

**Comment by hvoss49** [comment]
That works in all  cases. But:
```
\documentclass{article}
\usepackage{fontspec}
\setmainfont{texgyrepagella-regular.otf}
\begin{document}
\scshape Pagella
\end{document}
```

has no small caps. With xelatex it is fine and also with luatex 1.10.0. I
know that there were some
changes in the code of 1.10.1 regarding to loading fonts. Maybe I should
write to the luatex list.

Am Fr., 3. Mai 2019 um 02:12 Uhr schrieb Will Robertson <
notifications@github.com>:

**Comment by khaledhosny** [comment]
That is a bug in LuaTeX 1.10.1, see https://tug.org/pipermail/luatex/2019-May/007133.html

**Comment by wspr** [comment]
Thanks @khaledhosny , much appreciated.
