### ISSUE TITLE
language: dflt instead of DFLT

### ISSUE THREAD

**Issue by u-fischer** [wspr/fontspec#372]
## Description

The code for the harfbuzz module (https://github.com/khaledhosny/harf/blob/master/src/harf-luaotfload.lua)  contains the comment

       -- fontspec seems to incorrectly use “DFLT” for language instead of “dflt”.

I think this comment is correct. The specification (http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#4.b.ii) says

> DFLT is a valid value for the script tag, and dflt is not.
> dflt is a valid value for the language tag, and DFLT is not.

 

## Check/indicate
- [x] Relevant for XeTeX
- [x] Relevant for LuaTeX

**Comment by wspr** [comment]
Good old OpenType… apologies for the confusion.
