### ISSUE TITLE
No bfseries for Palatino nova Pro with luaLaTeX

### ISSUE THREAD

**Issue by allefeld** [wspr/fontspec#394]
## Description

`\bfseries` appears not to be correctly defined for *Palatino nova Pro* when using LuaLaTeX, while it is when using XeLaTeX.

## Check/indicate
- [ ] Relevant for XeTeX
- [x] Relevant for LuaTeX
- [x] Issue tracker has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate

## Minimal example demonstrating the issue

When I process this document
```
\documentclass{article}
\usepackage{fontspec}
\setmainfont{Palatino nova Pro}
\begin{document}
{\mdseries mdseries}
{\bfseries bfseries}
\end{document}
```

with XeLaTeX, I get as expected the following result:
![image](https://user-images.githubusercontent.com/1738353/70396207-ae9af580-19fe-11ea-953b-99a2255fc2c5.png)

However, when I process it with LuaLaTeX, I get
![image](https://user-images.githubusercontent.com/1738353/70396217-c5414c80-19fe-11ea-94b0-6646c6c71511.png)

As far as I can tell, this problem is specific to this font; for example it does not happen with *Times New Roman*. I searched the fontspec documentation for a possibly relevant difference between Xe & Lua, but didn't find anything.

## Further details

I'm using TeX Live as included in Debian 10.2, i.e. 2018.20190227-2. According to the log, this means LuaTeX 1.07.0 and fontspec 2.7b.

My installation of *Palatino nova Pro* includes
```
PalatinoNovaPro-Regular.otf
PalatinoNovaPro-Italic.otf
PalatinoNovaPro-Medium.otf
PalatinoNovaPro-MediumIt.otf
```
from version 1, 2009.

**Comment by wspr** [comment]
Sorry, this is a font/engine issue not a fontspec issue (see luaotfload). Generally for complex faces the heuristics have trouble detecting. FWIW on my machine right now I get something even more nonsensical from your minimal example — for mdseries it's titling and for bfseries it's one of the darker bolds.

For complex setups I strongly recommend making your own `palatino-nova.fontspec` file with contents like this:

```
\defaultfontfeatures[palatino-nova]{
  Extension   = .otf ,
  UprightFont = PalatinoNovaPro-Regular ,
  ItalicFont  = PalatinoNovaPro-Italic ,
  BoldFont    = PalatinoNovaPro-Medium   ,
  BoldItalicFont = PalatinoNovaPro-MediumIt ,
}
```

Then you just write `\setmainfont{palatino-nova}` and you can fine-tune the font shapes in the family as per your tastes.
