### ISSUE TITLE
combination of font and language selection results in "Error: font not found"

### ISSUE THREAD

**Issue by Jetlagger** [wspr/fontspec#401]
If certain languages are selected by polyglossia and certain fonts are selected by fontspec, fontspec cannot find the fonts. I have only tried a couple of font/language combinations so far.

Fonts that I tried that seem unaffected: Amiri, Source Serif Pro, Adobe Garamond Pro, NeueHaasGrotesk, Frutiger Next LT W1G.
Fonts that I tried that are affected in combination with some languages: Minion Pro, Arno Pro, EBGaramond(0.016).

(I haven't done more testing because I know very little about how these things work and wouldn't know what to look for, but it did occur to me that these three fonts that fail have in common that they contain optical sizes. Could be coincidental though..?)

Example (using LuaTeX with MiKTeX, log file is below):

```
\documentclass{article}
\usepackage{fontspec}
\setmainfont{EB Garamond}
\usepackage{polyglossia}
\setdefaultlanguage{german}
\begin{document}
foo
\end{document}
```
produces:
```
Package fontspec Error: The font "EBGaramond" cannot be found.
Package fontspec Warning: Language 'German' not available for font 'EBGaramond'
```

For example EB Garamond works with: english, czech, french, finnish, spanish, vietnamese... But it cannot be loaded with catalan or german.

Log: [langtest.log](https://github.com/wspr/fontspec/files/4049560/langtest.log)

**Comment by GilmourR** [comment]
This error is likely related. The following code gives ```! Undefined control sequence. <recently read> \setmainlanguage``` when ```setmainlanguage``` is uncommented.
[test3.log](https://github.com/wspr/fontspec/files/4052211/test3.log)
 

```
\documentclass{article}
\usepackage{fontspec}
\usepackage{xeCJK}
%\setmainlanguage{english}
%\setotherlanguage{chinese}
\setCJKmainfont{SimSun}
\setCJKsansfont{SimSun}

\begin{document}

東風

test
\end{document}
```

**Comment by e-kwsm** [comment]
I think this is a regression. The results with @Jetlagger's example are the following:

| LuaLaTeX | XeLaTeX | fontspec | work? |
|:--|:-:|:-:|:-:|
| 1.10.0                  | | 2019/10/19 v2.7d | Y |
| 1.11.2 (HB)             | | 2019/10/19 v2.7d | Y |
| | 3.14159265-2.6-0.999991 | 2019/10/19 v2.7d | Y |
| 1.10.0                  | | 2020/01/09 v2.7e | **N** |
| 1.11.2 (HB)             | | 2020/01/09 v2.7e | **N** |
| | 3.14159265-2.6-0.999991 | 2020/01/09 v2.7e | Y |

**Comment by u-fischer** [comment]
@Jetlagger's real error is not the font not found but the lua error earlier on. It is the same as in https://github.com/wspr/fontspec/issues/403.

**Comment by Jetlagger** [comment]
I believe the problem is reductible to (and better explained in) #403.
