### ISSUE TITLE
2.7i completely broken on LuaTeX

### ISSUE THREAD

**Issue by viktoriasee** [wspr/fontspec#415]
## Description
The current version distributed by CTAN/Miktex is completely broken for LuaTeX. On XeTeX it does not occur.
The error is `Undefined control sequence` in line 115 of `fontenc.sty`:
`\xdef\@fontenc@load@list{\@fontenc@load@list`

## Check/indicate
- [ ] Relevant for XeTeX
- [x] Relevant for LuaTeX
- [X] Issue tracker has been searched for similar issues?

## Minimal example demonstrating the issue
```latex
\documentclass{article}
\usepackage{fontspec}
\begin{document}
\end{document}
```

**Comment by eg9** [comment]
No problem here.

```
LaTeX2e <2020-02-02> patch level 4
Lua module: luaotfload-main 2020-02-02 3.12 luaotfload entry point
[...]
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
[...]
Package: fontspec 2020/02/21 v2.7i Font selection for XeLaTeX and LuaLaTeX
```

**Comment by viktoriasee** [comment]
The previous MikTeX update I did on Feb. 11th. Everything worked until today's update.
```
LaTeX2e <2019-10-01> patch level 3
Lua module: luaotfload-main 2020-02-02 3.12 luaotfload entry point
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
Package: fontspec 2020/02/21 v2.7i Font selection for XeLaTeX and LuaLaTeX
Package: fontenc 2020/02/11 v2.0o Standard LaTeX package
```
So I have an older LaTeX engine than you, Enrico @eg9. So whose bug is this?

**Comment by davidcarlisle** [comment]
@viktoriasee  

> So I have an older LaTeX engine than you, Enrico @eg9. So whose bug is this?

it will be a local configuration problem on your installation, most likely you have the sources for the current release (2020-02-02 Patch Level 4) but have not rebuilt the format files. I'm sorry I can not tell you the miktex configuration option to force the formats to rebuild (it would be `fmtutil-sys --all` in texlive)

**Comment by u-fischer** [comment]
You obviously don't have a current format. Normally miktex takes care to rebuild the formats, but it can fail. Try to build the format manually: Go to the miktex console (probably user mode), to settings, tab formats. Select the lualatex entry and click on build format.  If you get an error you should ask about it.

**Comment by viktoriasee** [comment]
Thank you for the help. But I do not get an error when building the lualatex format. I even reinstalled luatex and the error persists. Can anyone with MikTeX confirm whether all users are affected or just me?

**Comment by davidcarlisle** [comment]
do you now get LaTeX2e 2020-02-02 in the startup banner? If it is still showing a 2019 date then your format has not been updated and it can not work as you have newer 2020 versions of the input files which assume a 2020 format.

**Comment by viktoriasee** [comment]
No I did not. But the problem is solved. Updating the Lualatex format manually in user mode (not admin mode) did it. Thanks for the help again. This was more a MikTeX issue.
