### ISSUE TITLE
Strange result in ligature with Amiri font 

### ISSUE THREAD

**Issue by seloumi** [wspr/fontspec#427]
## Description
With `Amiri` font and `Script=Arabic` feature I obtain an incorrect result with words like "Scientifique"  It appears like this "Scientfiique" 

## Check/indicate
- [x] Relevant for XeTeX
- [ ] Relevant for LuaTeX
- [ ] Issue tracker has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate

## Minimal example demonstrating the issue

```latex
\documentclass{article}

\usepackage{fontspec}
\setmainfont[Script=Arabic]{Amiri}

\begin{document}

Scientifique
\qquad
{\addfontfeatures{Script=Latin} Scientifique}

\end{document}

```

## Result

![image](https://user-images.githubusercontent.com/8249073/85868350-6f7d9780-b7ca-11ea-9f75-5843867e1b95.png)

**Comment by u-fischer** [comment]
Well Script=Arabic is the wrong script to write something in Latin. Beside this I don't think that there is anything fontspec can do here, it is probably a font problem.

**Comment by seloumi** [comment]
@u-fischer  my document is in Arabic and I'm facing the issue when writing some Latin words

**Comment by seloumi** [comment]
@khaledhosny  may be you have an idea ?

**Comment by khaledhosny** [comment]
That is looks odd but expected, don’t use `Script=Arabic` for non-Arabic text, it will cause HarfBuzz to do layout from right to left, so it seems `if` as `fi` and makes it a ligature.

**Comment by khaledhosny** [comment]
Nothing here is specific to Amiri, you might not get it with most other fonts because Latin ligature lookups won’t be registered for Arabic script, but Amiri does (not purposefully, but because it simplifies font source).

**Comment by seloumi** [comment]
@khaledhosny  Thanks, so nothing to do here? just change to `Script=Latin` feature for every Latin words containing `if` ?

**Comment by khaledhosny** [comment]
Always use the correct script of the text, otherwise you will get broken layout. It might not be as obvious, but it will still be broken.

Of course, script should be detected automatically, but TeX lives in the previous century and no one gives a damn.

**Comment by u-fischer** [comment]
> Of course, script should be detected automatically, but TeX lives in the previous century and no one gives a damn.

Well luaotfload has a `multiscript=auto` option:

~~~~
\documentclass{article}

\usepackage{fontspec}


\begin{document}


\setmainfont[Renderer=HarfBuzz]{Amiri}
Scientifique  یہ ایک جملہ ہے

\setmainfont[Renderer=HarfBuzz,Script=Arabic]{Amiri}
Scientifique  یہ ایک جملہ ہے

\setmainfont[Renderer=HarfBuzz,RawFeature={multiscript=auto}]{Amiri}
Scientifique  یہ ایک جملہ ہے


\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/85880230-f8e99580-b7db-11ea-866f-d7a9620fa644.png)

**Comment by jbezos** [comment]
And with `babel`–`luatex`: https://github.com/latex3/babel/wiki/What's-new-in-babel-3.38 .
