### ISSUE TITLE
Wishlist: baseline adjustments for FakeBold

### ISSUE THREAD

**Issue by callegar** [wspr/fontspec#447]
## Description

FakeBold is an artificial font transformation and as such it will always represent a compromise. However, it can be quite useful when you miss a real bold version of the font you are using. There is usefulness also with unicode math fonts, since only XITS has a bold math version (e.g., if you need to put math in headings, abstracts typeset in bold or if you have some special notation that uses bold).

The issue with fake bold is that as a side effect of how it operates, it affects the font size and the baseline: the font becomes bigger and the baseline gets pushed down a bit. Would be great to have a way to tune the scale and baseline positioning to improve the visual aspect of faked bold. 

## Check/indicate
- [X] Relevant for XeTeX
- [X] Relevant for LuaTeX
- [X] Issue tracker has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate

## Minimal example demonstrating the issue

```LaTeX
\documentclass[a4paper,12pt]{article}
\usepackage[a4paper,body={17cm,25cm},nohead]{geometry}
\usepackage{amsmath}
\usepackage[mathup=sym]{unicode-math}
\setmainfont{Stix Two Text}
\setmathfont{Stix Two Math}[Scale=MatchLowercase,
  BoldFont=*, BoldFeatures={FakeBold=4, FakeStretch=1.15, Scale=0.95}]
\begin{document}
sin$\sin$\textbf{sin}$\boldsymbol{\sin}$ 

sin$\sin$\textbf{sin}\raisebox{0.3pt}{$\boldsymbol{\sin}$} 
\end{document}
```

As it can be seen below, with FakeBold there is significant baseline misalignment. There is also a scale error, but as shown in the example above it can be corrected with the scale=0.95 option. By also fixing the baseline, the faking of a bold font (in this case a bold math font) gets much better. Would be great to have a baselineadj=... option.

![image](https://user-images.githubusercontent.com/1041166/120842696-54d0a880-c56d-11eb-97f1-3004ae2c20b5.png)

**Comment by wspr** [comment]
Sorry, fontspec is only an interface to features offered by the xetex and LuaTeX engines. There’s no way from a macro level for fontspec to make changes like this (although luaotfload would be a good place to start in luatex).
