### ISSUE TITLE
No small caps with OTF font

### ISSUE THREAD

**Issue by interkosmos** [wspr/fontspec#450]
## Description
Small caps are not selected even if the OTF font provides such a style.

## Check/indicate
- [ ] Relevant for XeTeX
- [X] Relevant for LuaTeX
- [X] Issue tracker has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate

## Minimal example demonstrating the issue
```
\documentclass[paper=a4]{scrreprt}

\usepackage{fontspec}
\setmainfont{Minion Pro}

\usepackage{polyglossia}
\setmainlanguage{german}

\begin{document}
\textsc{No small caps}
\end{document}
```

## Further details
The Minion Pro OTF font includes small caps:

```
$ otfinfo -f ~/.fonts/Minion\ Pro/MinionPro-Regular.otf
aalt    Access All Alternates
c2sc    Small Capitals From Capitals
case    Case-Sensitive Forms
cpsp    Capital Spacing
dlig    Discretionary Ligatures
dnom    Denominators
fina    Terminal Forms
frac    Fractions
hist    Historical Forms
kern    Kerning
liga    Standard Ligatures
lnum    Lining Figures
numr    Numerators
onum    Oldstyle Figures
ordn    Ordinals
ornm    Ornaments
pnum    Proportional Figures
salt    Stylistic Alternates
sinf    Scientific Inferiors
size    Optical Size
smcp    Small Capitals
sups    Superscript
swsh    Swash
tnum    Tabular Figures
xx01    <unknown feature>
zero    Slashed Zero
```
In contrast, fontspec does not recognise the style:
```
LaTeX Font Warning: Font shape `TU/MinionPro(1)/m/sc' undefined
(Font)              using `TU/MinionPro(1)/m/n' instead on input line 15.

[1{/usr/local/texlive/2021/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]
(./test.aux)

LaTeX Font Warning: Some font shapes were not available, defaults substituted.
```

**Comment by wspr** [comment]
Thanks for logging the issue. This must be due to something changing outside of fontspec — it’s not possible that this has been broken for ever…

**Comment by zauguin** [comment]
This is not a bug in fontspec, it's an odd font configuration. Minion Pro has the small caps feature for the default language of the Latin script, but it has a special feature table for german which overwrites the default in german documents. The german table only supports the discretionary ligatures feature, not small caps.

**Comment by interkosmos** [comment]
Thank you very much for your explanation.
