### ISSUE TITLE
\textsw and \swshape

### ISSUE THREAD

**Issue by hvoss49** [wspr/fontspec#455]
## Description

Only for lualatex/xelatex. For pdflatex it works

The new command \textsw works but \swshape not:

## Check/indicate
- [x] Relevant for XeTeX
- [x] Relevant for LuaTeX
- [x] Issue tracker has been searched for similar issues?
- [] Links to <tex.stackexchange.com> discussion if appropriate

## Minimal example demonstrating the issue
```
\documentclass{report}
\usepackage{garamondlibre}
\listfiles

\begin{document}

\textsw{ABCDEFGHIJKLMNOPQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz}

%\addfontfeature{Style=Swash}%   works
\swshape                     % does not work
ABCDEFGHIJKLMNOPQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz

\end{document}
```

## Further details
Up-to-date TL2021

**Comment by u-fischer** [comment]
garamondlibre redefines `\textsw` and adds swash support there, but it doesn't define `\swshape` but `\swashshape`. Imho this should be reported to `garamondlibre`.

If you want to use it with fontspec directly you have to correctly setup the font and the features, e.g.

~~~~
\documentclass{report}
\usepackage{fontspec}
\setmainfont{GaramondLibre}[
  SwashFont = {GaramondLibre-Italic} ,
  SwashFeatures = {Style=Swash}]


\begin{document}

\textsw{ABCDEFGHIJKLMNOPQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz}

\swshape                     
ABCDEFGHIJKLMNOPQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz

\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/149753835-fdb65afe-9761-4153-9597-d6b15a7d5d73.png)
