### ISSUE TITLE
GPOS/GSUB tables should not be used for detecting script support

### ISSUE THREAD

**Issue by simoncozens** [wspr/fontspec#507]
## Description
A sentence or two describing the issue.

## Check/indicate
- [X] Relevant for XeTeX
- [X] Relevant for LuaTeX
- [X] Issue tracker has been searched for similar issues? (#48 is similar)
- [X] Links to <tex.stackexchange.com> discussion if appropriate: https://tex.stackexchange.com/questions/715438/error-loading-noto-sans-imperial-aramaic-does-not-contain-imperial-aramaic

## Minimal example demonstrating the issue
```
\documentclass{article}
\newfontfamily\aramaicfont[Script=Imperial Aramaic,
        Path=fonts/,
        UprightFont=*-Regular,
        Extension=.otf]{Noto Sans Imperial Aramaic}
\begin{document}
hello \emph{hello}
\end{document}
```

## Further details

There are various good ways of detecting script support: Ideally you can look at the set of Unicode codepoints available in the font; you can look at the Unicode codepage ranges defined in the OS/2 table; you could even look for dlng and  slng tags in the meta table.

fontspec is instead looking at the script records / language systems defined in the `GSUB`/`GPOS` tables. But this is not a good way of detecting script support, since script records in those tables are only needed when OpenType Layout behaviour needs to be applied - sometimes, as in this font, scripts can be supported without needing OTL shaping.

**Comment by davidcarlisle** [comment]
fontspec isn't really detecting anything here:  the user call is specifying `Script=Imperial Aramaic,` so explicitly requesting a font with the `script` set, if that isn't used the font will still load and the Aramaic code points can be used without problem.

```
\documentclass{article}
\usepackage{fontspec}
\newfontfamily\aramaicfont[
%Script=Imperial Aramaic,
]{Noto Sans Imperial Aramaic-Regular.ttf}
\begin{document}
hello \emph{hello}
\end{document}
```

loads the font with no warning (I had  a ttf rather than otf file but that's unrelated to the issue) You do get the warning if you uncomment `Script=Imperial Aramaic,`

however it's only a warning and doesn't affect the output.

```
Package fontspec Warning: Font "NotoSansImperialAramaic-Regular" does not
(fontspec)                contain requested Script "Imperial Aramaic".
```

Maybe this distinnction needs better documentation but I'm not sure any code change is needed (personal view: it's @wspr  call really)

**Comment by simoncozens** [comment]
> so explicitly requesting a font with the script set

Right. What I'm saying is: what does it mean to request a font with the script set? Because currently that means looking in the OTL tables, and I think that's the wrong place to look.

**Comment by wspr** [comment]
@simoncozens  — writing "Script=XX" is the ostensibly user-friendly way to write `script=zz` in the underlying font loading mechanism (XeTeX or luaotfload), where `zz` is given by one of these: https://learn.microsoft.com/en-us/typography/opentype/spec/scripttags

This is only needed for multi-script fonts where certain OpenType font features or shaping rules will only be activated in specific scripts.

I presume (I don't have a lot of experience in this area) that single-script fonts will often not worry about the distinction and loading a script-specific font with default settings to typeset something in that specific script will usually yield correct results.

**Comment by wspr** [comment]
I should also add that OpenType features are defined hierarchically and it is possible for some features to only be available for certain scripts (and/or languages). In these cases the script must be explicitly chosen for a particularly script-related feature to be available.

**Comment by wspr** [comment]
Let me know if you think the changes to this warning in the commit above are enough, or if the typeset documentation should also be changed...

**Comment by simoncozens** [comment]
Ah, I understand - you are using fontspec both for finding and selecting fonts, and also for passing parameters to Harfbuzz. Yes, the warning changes seem fine.

**Comment by wspr** [comment]
@khaledhosny  @zauguin  — I'm looking into the change requested by Khaled above that scripts requested are passed through  to the font renderer regardless of whether the font supports it or not.

From your perspective, when no script/language is requested is it okay or appropriate to use

    script=DFLT
    language=dflt

? Previously fontspec didn't include these but I think it's slightly simpler/clearer to always add them explicitly. What do you think?

**Comment by khaledhosny** [comment]
I think for HarfBuzz, setting the script to `DFLT` is the same as not setting it (HarfBuzz shaping APIs take ISO 15924 script tags as input, so the OpenType scripts fontspec uses gets translated to ISO 15924 tags, and `DFLT` gets translated to `0`, which is the initial value already).

**Comment by wspr** [comment]
@khaledhosny  — thanks very much, I'll proceed like this and then we can see if any bug reports start rolling through :)
