### ISSUE TITLE
luaotfload complains about not finding a file with an absolute path

### ISSUE THREAD

**Issue by avidseeker** [wspr/fontspec#527]
## Description
Title.

## Check/indicate
- [ ] Relevant for XeTeX
- [x] Relevant for LuaTeX
- [x] Issue tracker has been searched for similar issues?
- [x] Links to <tex.stackexchange.com> discussion if appropriate

## Minimal example demonstrating the issue
```
\documentclass[mla8]{mla}
\usepackage{fontspec}
\setmainfont{FreeSerif}
\fontspec{NotoColorEmoji}[
	Extension=.ttf,
	Path=/usr/share/texmf-dist/fonts/truetype/google/noto-emoji/,
	RawFeature={mode=harf}
]
\setmainfont{NotoColorEmoji}
\setmainfont[Script=Arabic]{ScheherazadeNew}

\begin{document}
\begin{paper}
🤔
\end{paper}
\end{document}
```

Checking luaotftool:

```sh
$ luaotfload-tool --find="Noto Color Emoji"
luaotfload | resolve : Font "Noto Color Emoji" found!
luaotfload | resolve : Resolved file name "/usr/share/texmf-dist/fonts/truetype/google/noto-emoji/NotoColorEmoji.ttf"
```

However, using lualatex to compile the document:

```
...
luaotfload | db : Reload initiated (formats: otf,ttf,ttc); reason: File not found: "NotoColorEmoji.otf".
```

luaotfload doesn't complain when documentclass is article. I tried checking what could be the potential problem with [mla.cls](https://gitlab.com/ssterling/mlacls/-/blob/master/mla.dtx?ref_type=heads), but it doesn't seem to tweak anything about fonts.

## Further details
* [Original TeX SE discussion](https://tex.stackexchange.com/questions/722371)
* https://github.com/latex3/luaotfload/issues/277
* [mla.cls issue](https://gitlab.com/ssterling/mlacls/-/issues/12)

**Comment by wspr** [comment]
Looking at the answer by egreg: https://tex.stackexchange.com/a/722870/179

This is an error with an external font package which is loaded by mla. What could fontspec do to improve this?

**Comment by avidseeker** [comment]
Sorry, I submitted this issue before I found out the answer.

**Comment by wspr** [comment]
@eg9 — do you think it would be reasonable for fontspec to add a global end package hook to clear the default font features? Document that should be a user feature only. 

If so, could consider adding a \globalfontfeatures option as well which behaves in the current “unsafe” manner

**Comment by wspr** [comment]
@avidseeker — no worries at all, thanks for filing bugs about it
