### ISSUE TITLE
fontspec causing crash with XeTeX

### ISSUE THREAD

**Issue by suetzjoh** [wspr/fontspec#535]
## Description
Compiling any document with the package `fontspec` loaded throws `Undefined control sequence: \strongfontdeclare`.

## Check/indicate
- [x] Relevant for XeTeX
- [x] Issue tracker has been searched for similar issues?
- compare https://tex.stackexchange.com/questions/722711/fontspec-crashes-with-undefined-control-sequence-from-strongfontdeclare

## Minimal example demonstrating the issue
```
\documentclass{scrartcl} 

\usepackage{fontspec}

\begin{document}
	abc
\end{document}
```

## Further details

Fontspec started throwing errors when compiling with XeTeX on a new machine. Previously people have been able to solve this issue by updating the packages, but my packages are all up to date, l3backend has the version of 27.05., l3kernel from 09.11. and l3packages from 31.08. 

I’m using MiKTeX Console 4.12 and TeXstudio 4.8.4. On my previous machine I was using fontspec v2.8e and MiKTeX Console 4.12. Funnily enough after updating the packages over there I can’t open MiKTeX Console "because no Qt platform plugin could be initialized" nor compile any document but I assume that’s a separate problem.

Here are the first few lines of a recent log file which I assume are relevant.

```
This is XeTeX, Version 3.141592653-2.6-0.999996 (MiKTeX 24.4) (preloaded format=xelatex 2024.12.3)  3 DEC 2024 17:16
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**./document.tex
(document.tex
LaTeX2e <2024-11-01>
L3 programming layer <2024-01-04>
(C:/Users/Hannes/Documents/MiKTeX/2.9\tex/latex/koma-script\scrartcl.cls
Document Class: scrartcl 2023/07/07 v3.41 KOMA-Script document class (article)
(C:/Users/Hannes/Documents/MiKTeX/2.9\tex/latex/koma-script\scrkbase.sty
Package: scrkbase 2023/07/07 v3.41 KOMA-Script package (KOMA-Script-dependent b
asics and keyval usage)
```

**Comment by u-fischer** [comment]
Your system contains outdated packages. E.g. scrartcl.cls should have version 2024/10/24 v3.43. 

Repair the miktex console (see https://github.com/MiKTeX/miktex/issues/1486#issuecomment-2084843465) and check for updates in user and admin mode.

**Comment by suetzjoh** [comment]
Okay, thanks to your comment, I found out that the issue was caused by the outdated packages being included in my custom texmf directory, which included the l3 programming layer and the koma-script. Even though MiKTeX had installed the proper version, it accessed the older version first. Deleting those folders from the texmf directory fixed the issue.
