### ISSUE TITLE
All options should have an "Off" key

### ISSUE THREAD

**Issue by khaledhosny** [wspr/fontspec#82]
For consistency, all options should have an "Off" key so one can say `Ligatures=Off` and turn off all ligatures (equivalent to `Ligatures={NoRequired,NoCommon,NoContextual}`) and so on.

**Comment by wspr** [comment]
Again sorry for the slow reply!! This is happening in the next release. (With current interface `Ligatures=ResetAll`.) Actually… maybe this isn't quite what you asked for. `ResetAll` removes all +onum AND -onum etc. etc. Do you think a global "off" still makes sense?

**Comment by khaledhosny** [comment]
I think this can be closed now.
