### ISSUE TITLE
Fontspec sets  \baselineskip

### ISSUE THREAD

**Issue by hrpunio** [wspr/fontspec#88]
```latex
\documentclass{article}

\showthe\baselineskip %% shows 12pt

%% Package: fontspec 2010/09/29 v2.1b
\usepackage{fontspec}

\showthe\baselineskip %% now 10pt
```

The problem (minor) occurs when someone wants to
set textweight as multiplicity of `baselineskip`

Is this feature intentional?

--t

**Comment by wspr** [comment]
This has now (finally!!!) been fixed. Sorry for the very very very slow reply.
